#!/usr/bin/env python3
"""Reproduce the half-band tables in editor/OversamplingCoefficients.hpp.

Uses only Python's standard library. Kaiser window formula:
https://www.dsprelated.com/freebooks/sasp/Kaiser_Window.html
The center coefficient is 1/2; odd coefficients are normalized to sum to 1/2.
Only the first half of the symmetric odd phase is stored.
"""
import math
from pathlib import Path


def i0(x):
    term = result = 1.0
    for k in range(1, 100):
        term *= (x / (2 * k)) ** 2
        result += term
        if term < result * 1e-17:
            break
    return result


def coefficients(length, beta):
    center = (length - 1) // 2
    values = []
    for i in range(1, length, 2):
        n = i - center
        ideal = math.sin(math.pi * n / 2) / (math.pi * n)
        values.append(ideal * i0(beta * math.sqrt(1 - (n / center) ** 2)) / i0(beta))
    scale = .5 / sum(values)
    return [x * scale for x in values[:len(values) // 2]]


if __name__ == "__main__":
    output = ["// Generated by mac/Tools/oversampling_coefficients.py; do not edit by hand.",
              "#pragma once", "#include <array>", "namespace Tracker::OversamplingTables {"]
    for name, length, beta in [("first", 145, 11), ("second", 49, 13), ("later", 33, 13)]:
        values = coefficients(length, beta)
        output.append(f"// {length} taps; Kaiser beta {beta}.")
        output.append(f"inline constexpr std::array<double, {len(values)}> {name}{{{{")
        output.extend(f"  {x:.17g}," for x in values)
        output.append("}};")
    output.append("}")
    (Path(__file__).resolve().parents[2] / "editor/OversamplingCoefficients.hpp").write_text("\n".join(output) + "\n")
