#include "../App/ArrangementMatrixWindow.hpp"
#include "PrivateGuiTest.hpp"
#include <iostream>

namespace {
using Json=ScreamSeq::Api::Json;
void require(bool value,const char *message){if(!value)throw std::runtime_error(message);}
struct Owner {
  HWND window{},edit{};
  Owner(){WNDCLASSW type{};type.lpfnWndProc=DefWindowProcW;type.hInstance=GetModuleHandleW(nullptr);type.lpszClassName=L"ScreamSeq.Matrix.TestOwner";RegisterClassW(&type);window=CreateWindowW(type.lpszClassName,L"Owned matrix fixture",WS_OVERLAPPEDWINDOW|WS_VISIBLE,0,0,1100,800,nullptr,nullptr,type.hInstance,nullptr);require(window,"Create matrix owner");ScreamSeq::Tests::ownGuiWindow(window);edit=CreateWindowW(L"EDIT",L"Unrelated retained field",WS_CHILD|WS_VISIBLE|WS_TABSTOP,0,0,200,24,window,nullptr,type.hInstance,nullptr);require(edit,"Create unrelated owner field");ScreamSeq::Tests::ownGuiWindow(edit);}
  ~Owner(){if(window)DestroyWindow(window);}
  void close(){const auto previous=window,field=edit;require(DestroyWindow(window),"Destroy matrix owner");window=edit=nullptr;require(!IsWindow(previous)&&!IsWindow(field),"Matrix owner survived destruction");}
};
Json initial(){return {{"documentId","song-a"},{"revision","r0"},{"busy",false},{"selectedOrderID","o1"},{"selectedTrackID","t0"},{"document",{{"editable",true},{"channels",25},{"sequence",0},{"sequences",Json::array({{{"id","s0"},{"index",0}},{{"id","s1"},{"index",1}}})}}}};}
struct Fixture {
  Json state=initial();unsigned totalOrders=130,writeCount=0;std::vector<std::pair<std::string,Json>> requests;std::vector<std::pair<std::string,std::string>> opened;unsigned returned=0;
  std::function<Json(std::string,Json)> intercept;
  ScreamSeq::ArrangementMatrixWindow tool;
  explicit Fixture(HWND owner):tool(owner,{[this](std::string method,Json params){return operate(std::move(method),std::move(params));},[this](std::string order,std::string track){opened.emplace_back(std::move(order),std::move(track));},[this]{++returned;}}){ScreamSeq::Tests::ownGuiWindow(tool.window());}
  HWND control(int id){const auto value=GetDlgItem(tool.window(),id);require(value,"Missing matrix control");return value;}
  void click(int id){SendMessageW(tool.window(),WM_COMMAND,MAKEWPARAM(id,BN_CLICKED),reinterpret_cast<LPARAM>(control(id)));}
  void select(int row,int column=1){NMITEMACTIVATE notice{};notice.hdr={control(8401),8401,NM_CLICK};notice.iItem=row;notice.iSubItem=column;SendMessageW(tool.window(),WM_NOTIFY,8401,reinterpret_cast<LPARAM>(&notice));}
  void mode(int value){SendMessageW(control(8410),CB_SETCURSEL,value,0);SendMessageW(tool.window(),WM_COMMAND,MAKEWPARAM(8410,CBN_SELCHANGE),reinterpret_cast<LPARAM>(control(8410)));}
  void postedRefreshes(){MSG message{};unsigned count=0;while(PeekMessageW(&message,tool.window(),WM_APP+186,WM_APP+186,PM_REMOVE)){require(++count<=8,"Matrix automatic refresh queue did not settle");DispatchMessageW(&message);}}
  std::wstring cell(int row,int column){wchar_t buffer[1024]{};NMLVDISPINFOW info{};info.hdr={control(8401),8401,LVN_GETDISPINFOW};info.item={};info.item.mask=LVIF_TEXT;info.item.iItem=row;info.item.iSubItem=column;info.item.pszText=buffer;info.item.cchTextMax=1024;SendMessageW(tool.window(),WM_NOTIFY,8401,reinterpret_cast<LPARAM>(&info));return buffer;}
  Json matrix(const Json &params){
    const auto start=params.at("startOrder").get<unsigned>(),channel=params.at("startChannel").get<unsigned>(),count=params.at("channelCount").get<unsigned>();const auto channels=state["document"]["channels"].get<unsigned>();require(params.at("orderCount")==64&&count>0&&count<=12&&channel+count<=channels,"UI exceeded 64 x 12 bounded matrix request");
    Json tracks=Json::array(),orders=Json::array();for(unsigned c=channel;c<channel+count;++c)tracks.push_back({{"id","t"+std::to_string(c)},{"channel",c},{"name",c==0?"Long track / café / 旋律":"Track"}});
    for(unsigned r=start;r<std::min(start+64,totalOrders);++r){const bool sentinel=r==2||r==3;Json order={{"id","o"+std::to_string(r)},{"order",r},{"pattern",r==2?65534:r==3?65535:r%2},{"name",r%16==0?"Section / café / 旋律":""},{"rows",sentinel?0:64},{"blocks",Json::array()}};
      if(!sentinel){order["patternID"]="p"+std::to_string(r%2);order["patternName"]="Long repeated pattern / café / 旋律";for(unsigned c=channel;c<channel+count;++c){Json bins=Json::array();for(unsigned i=0;i<16;++i)bins.push_back(i==0?3:0);order["blocks"].push_back({{"channel",c},{"trackID","t"+std::to_string(c)},{"events",3},{"notes",1},{"trackerEvents",1},{"preciseEvents",1},{"nativeFxEvents",1},{"bins",std::move(bins)}});}}
      orders.push_back(std::move(order));}
    return {{"orders",std::move(orders)},{"tracks",std::move(tracks)},{"totalOrders",totalOrders},{"totalChannels",channels},{"startOrder",start},{"startChannel",channel}};
  }
  Json operate(std::string method,Json params){requests.emplace_back(method,params);if(intercept)return intercept(std::move(method),std::move(params));if(method=="arrangement.matrix")return {{"state",state},{"result",matrix(params)}};require(method=="arrangement.copyBlock","Unexpected matrix operation");require(params.at("expectedRevision")==state.at("revision"),"Copy silently rebased its captured revision");++writeCount;state["revision"]="r"+std::to_string(writeCount);return {{"state",state},{"result",{{"wouldChange",true},{"changedCells",0},{"targetOrder",params.at("targetOrder")},{"targetPattern",1},{"clonesPattern",true},{"dryRun",false}}}};}
  void key(WPARAM key,bool ctrl=false,bool shift=false,bool alt=false){BYTE previous[256]{},next[256]{};require(GetKeyboardState(previous),"Read private keyboard state");std::copy(std::begin(previous),std::end(previous),std::begin(next));next[VK_CONTROL]=ctrl?0x80:0;next[VK_SHIFT]=shift?0x80:0;next[VK_MENU]=alt?0x80:0;require(SetKeyboardState(next),"Set private keyboard state");struct Restore{BYTE *state;~Restore(){SetKeyboardState(state);}}restore{previous};SendMessageW(GetFocus(),WM_KEYDOWN,key,0);}
};
void densityAndKeyboard(Owner &owner){
  Fixture f(owner.window);f.tool.open(f.state);auto snapshot=f.tool.snapshot();require(snapshot["fresh"].get<bool>()&&snapshot["orderCount"]==64&&snapshot["trackCount"]==12&&snapshot["selectedOrderID"]=="o1"&&snapshot["selectedTrackID"]=="t0","First matrix page lost bounded shape or stable initial selection");require(Header_GetItemCount(ListView_GetHeader(f.control(8401)))==13,"Matrix omitted track columns");
  const auto accessible=f.cell(0,1);require(accessible.find(L"1 notes")!=std::wstring::npos&&accessible.find(L"3 events")!=std::wstring::npos&&accessible.find(L"precise 1")!=std::wstring::npos&&accessible.find(L"FX 1")!=std::wstring::npos,"Accessible matrix text hid precise/FX density");require(f.cell(0,0).find(L"Section")!=std::wstring::npos,"Order label omitted its section");require(f.cell(2,0).find(L"Skip")!=std::wstring::npos&&f.cell(3,0).find(L"Stop")!=std::wstring::npos&&f.cell(3,1)==L"—","Sentinel rows became musical blocks");
  f.select(2);const auto count=f.requests.size();f.click(8407);f.click(8408);f.click(8409);require(f.opened.empty()&&f.requests.size()==count&&!IsWindowEnabled(f.control(8408)),"Sentinel accepted Open/Copy/Paste");
  f.select(4,3);SetActiveWindow(f.tool.window());SetFocus(f.control(8401));f.key(VK_RIGHT);require(f.tool.snapshot()["selectedOrderID"]=="o4"&&f.tool.snapshot()["selectedTrackID"]=="t3","Right arrow changed the wrong matrix coordinate");f.key(VK_DOWN);require(f.tool.snapshot()["selectedOrderID"]=="o5","Native row keyboard did not update stable selection");f.key(VK_RETURN);require(f.opened==std::vector<std::pair<std::string,std::string>>{{"o5","t3"}},"Open did not carry selected stable occurrence and track");
  f.key('C',true);require(f.tool.snapshot()["copied"]["orderID"]=="o5"&&f.tool.snapshot()["copied"]["trackID"]=="t3","Ctrl+C lost private copied source");f.select(6,5);f.key('V',true);require(f.writeCount==1&&f.requests.back().first=="arrangement.copyBlock"&&f.requests.back().second["sourceOrder"]==5&&f.requests.back().second["sourceChannel"]==3&&f.requests.back().second["targetOrder"]==6&&f.requests.back().second["targetChannel"]==4,"Ctrl+V changed captured source/target coordinates");require(f.tool.snapshot()["copied"].is_null(),"Accepted unchanged copy intention was retained as fresh");f.tool.refresh();require(f.tool.snapshot()["selectedOrderID"]=="o6"&&f.tool.snapshot()["selectedTrackID"]=="t4","Refresh changed independent matrix selection");
  const auto returns=f.returned;f.key(VK_F6,false,false,true);require(f.returned==returns,"Alt+F6 was stolen as local Return");f.key(VK_F6);require(f.returned==returns+1&&!f.tool.visible(),"F6 did not return to pattern");const auto writes=f.writeCount;SendMessageW(f.control(8401),WM_KEYDOWN,VK_RETURN,0);require(f.opened.size()==1&&f.writeCount==writes,"Hidden queued key activated a matrix action");
}
void retainedCopyAndStale(Owner &owner){
  Fixture f(owner.window);f.tool.open(f.state);f.select(0,2);f.click(8408);const auto copied=f.tool.snapshot()["copied"];f.mode(2);f.click(8411);f.click(8412);f.select(8,6);
  SetActiveWindow(f.tool.window());SetFocus(f.control(8410));f.tool.hide();f.tool.open(f.state);require(f.tool.snapshot()["copied"]==copied&&f.tool.snapshot()["mode"]=="mix"&&!f.tool.snapshot()["makeUnique"].get<bool>()&&f.tool.snapshot()["clip"].get<bool>()&&f.tool.snapshot()["selectedOrderID"]=="o8"&&GetFocus()==f.control(8410),"Reopen reset copied source/options/selection/focus");
  f.state["busy"]=true;f.tool.update(f.state);const auto beforeBusy=f.requests.size();f.click(8409);require(f.requests.size()==beforeBusy&&f.tool.snapshot()["copied"]==copied&&GetFocus()==f.control(8410),"Unchanged-revision busy poll changed retained draft/focus or submitted Paste");f.state["busy"]=false;f.tool.update(f.state);
  f.state["revision"]="external";f.tool.update(f.state);require(f.tool.snapshot()["copied"]["stale"].get<bool>()&&!IsWindowEnabled(f.control(8409)),"External edit silently rebased copied source");const auto writes=f.writeCount;f.click(8409);require(f.writeCount==writes&&f.tool.snapshot()["copied"]["orderID"]=="o0","Stale copy was applied or discarded");f.tool.refresh();require(f.tool.snapshot()["fresh"].get<bool>()&&f.tool.snapshot()["copied"]["stale"].get<bool>(),"Refresh rebased stale copy");
  f.click(8408);f.select(9,7);f.click(8409);const auto request=f.requests.back().second;require(request["mode"]=="mix"&&!request["makeUnique"].get<bool>()&&request["clip"].get<bool>()&&request["expectedRevision"]=="external"&&request["sourceOrder"]==8&&request["sourceChannel"]==5,"Recopy failed to capture exact options/current source");f.tool.refresh();f.click(8408);
  auto other=f.state;other["document"]["sequence"]=1;f.tool.update(other);require(f.tool.snapshot()["copied"]["stale"].get<bool>()&&f.tool.snapshot()["copied"]["sequenceID"]=="s0","Sequence change redirected source token");f.state=other;f.tool.refresh();require(f.tool.snapshot()["copied"]["stale"].get<bool>(),"New sequence refresh rebased source");
  other["documentId"]="replacement";other["revision"]="r0";f.state=other;f.tool.update(other);require(f.tool.snapshot()["copied"]["documentId"]=="song-a"&&f.tool.snapshot()["copied"]["stale"].get<bool>(),"Replacement reused copied source identities");f.click(8413);require(f.tool.snapshot()["copied"].is_null(),"Explicit Clear copy failed");
}
void pagingRetentionAndBounds(Owner &owner){
  Fixture f(owner.window);f.tool.open(f.state);f.click(8403);require(f.tool.snapshot()["startOrder"]==64&&f.tool.snapshot()["selectedOrderID"]=="o64","Later orders did not use 64-row page");ListView_Scroll(f.control(8401),1000,0);require(GetScrollPos(f.control(8401),SB_HORZ)>0,"Track-page reveal fixture did not scroll horizontally");f.click(8405);require(f.tool.snapshot()["startChannel"]==12&&f.tool.snapshot()["trackCount"]==12&&GetScrollPos(f.control(8401),SB_HORZ)==0,"Next tracks did not show its first selected track after horizontal scrolling");RECT firstTrack{},listClient{};Header_GetItemRect(ListView_GetHeader(f.control(8401)),1,&firstTrack);MapWindowPoints(ListView_GetHeader(f.control(8401)),f.control(8401),reinterpret_cast<POINT *>(&firstTrack),2);GetClientRect(f.control(8401),&listClient);require(firstTrack.left>=0&&firstTrack.right<=listClient.right,"Selected first track remains outside new page viewport");f.click(8405);require(f.tool.snapshot()["startChannel"]==24&&f.tool.snapshot()["trackCount"]==1&&!IsWindowEnabled(f.control(8405)),"Final track page did not clip to remaining tracks");f.click(8403);require(f.tool.snapshot()["startOrder"]==128&&f.tool.snapshot()["orderCount"]==2&&!IsWindowEnabled(f.control(8403)),"Final order page did not clip to remaining orders");
  f.click(8402);f.click(8404);f.select(35,5);ListView_EnsureVisible(f.control(8401),40,FALSE);ListView_Scroll(f.control(8401),230,0);const auto top=ListView_GetTopIndex(f.control(8401));const auto horizontal=GetScrollPos(f.control(8401),SB_HORZ);const auto chosen=f.tool.snapshot()["selectedOrderID"];
  SetActiveWindow(owner.window);SetFocus(owner.edit);const auto requests=f.requests.size();f.tool.update(f.state);require(f.requests.size()==requests&&GetFocus()==owner.edit&&ListView_GetTopIndex(f.control(8401))==top&&GetScrollPos(f.control(8401),SB_HORZ)==horizontal&&f.tool.snapshot()["selectedOrderID"]==chosen,"Unchanged poll queried worker, reset scroll/selection or stole focus");
  f.tool.refresh();require(GetFocus()==owner.edit&&ListView_GetTopIndex(f.control(8401))==top&&GetScrollPos(f.control(8401),SB_HORZ)==horizontal,"Explicit unchanged refresh reset scroll or stole unrelated focus");
  MINMAXINFO minimum{};SendMessageW(f.tool.window(),WM_GETMINMAXINFO,0,reinterpret_cast<LPARAM>(&minimum));SetWindowPos(f.tool.window(),nullptr,0,0,minimum.ptMinTrackSize.x,minimum.ptMinTrackSize.y,SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE);RECT client{};GetClientRect(f.tool.window(),&client);const auto dpi=GetDpiForWindow(f.tool.window());require(client.right==MulDiv(900,dpi,96)&&client.bottom==MulDiv(620,dpi,96),"Matrix minimum client changed");std::vector<RECT> boxes;for(HWND child=GetWindow(f.tool.window(),GW_CHILD);child;child=GetWindow(child,GW_HWNDNEXT)){if(!IsWindowVisible(child))continue;RECT box{};GetWindowRect(child,&box);MapWindowPoints(nullptr,f.tool.window(),reinterpret_cast<POINT *>(&box),2);require(box.left>=0&&box.top>=0&&box.right<=client.right&&box.bottom<=client.bottom&&box.right>box.left&&box.bottom>box.top,"Matrix control escaped minimum client");for(const auto &previous:boxes){RECT overlap{};require(!IntersectRect(&overlap,&box,&previous),"Matrix native controls overlap at minimum");}boxes.push_back(box);}
  for(UINT message:{WM_SETTINGCHANGE,WM_THEMECHANGED,WM_SYSCOLORCHANGE}){ListView_SetBkColor(f.control(8401),RGB(255,0,255));SendMessageW(f.tool.window(),message,0,0);require(ListView_GetBkColor(f.control(8401))==ScreamSeq::NativeReportList::palette(ScreamSeq::NativeControls::highContrast()).background,"Matrix top-level theme message did not refresh native list");require(GetFocus()==owner.edit&&f.tool.snapshot()["selectedOrderID"]==chosen,"Theme message changed unrelated focus or matrix selection");}
  std::cout<<"Matrix minimum 900 x 620 DIPs at "<<dpi<<" DPI; native scroll/selection retained\n";
}
void pumpedRequestsAndInvalidData(Owner &owner){
  Fixture f(owner.window);f.tool.open(f.state);f.select(0,2);f.click(8408);f.select(8,3);const auto old=f.state;
  f.intercept=[&](std::string method,Json params){require(method=="arrangement.copyBlock"&&params["sourceOrder"]==0&&params["targetOrder"]==8,"Pumped Paste captured wrong target");require(f.tool.snapshot()["pending"].get<bool>(),"Pending matrix request was not visible");f.click(8413);f.mode(1);f.click(8412);const auto count=f.requests.size();f.click(8409);require(f.requests.size()==count,"Pumped Paste submitted a duplicate write");auto accepted=f.state;accepted["revision"]="own-result";f.state=accepted;f.tool.update(accepted);return Json{{"state",accepted},{"result",{{"wouldChange",true}}}};};f.click(8409);require(f.tool.snapshot()["copied"].is_null()&&f.tool.snapshot()["mode"]=="merge"&&f.tool.snapshot()["clip"].get<bool>()&&!f.tool.snapshot()["pending"].get<bool>(),"Pumped completion reset a newer option or Clear copy action");
  f.intercept={};f.tool.refresh();f.click(8408);const auto copied=f.tool.snapshot()["copied"];
  f.intercept=[&](std::string,Json){auto replacement=old;replacement["documentId"]="new-song";replacement["revision"]="new-r0";f.state=replacement;f.tool.update(replacement);auto obsolete=old;obsolete["revision"]="old-result";return Json{{"state",obsolete},{"result",{{"wouldChange",true}}}};};f.click(8409);require(f.tool.snapshot()["documentId"]=="new-song"&&f.tool.snapshot()["revision"]=="new-r0"&&f.tool.snapshot()["copied"]["generation"]==copied["generation"]&&!f.tool.snapshot()["pending"].get<bool>(),"Old-document completion published or destroyed retained copy");
  f.intercept={};f.tool.refresh();const auto before=f.tool.snapshot();f.intercept=[&](std::string method,Json params){require(method=="arrangement.matrix","Invalid data fixture expected read");auto data=f.matrix(params);data["orders"][1]["id"]=data["orders"][0]["id"];return Json{{"state",f.state},{"result",std::move(data)}};};f.tool.refresh();const auto after=f.tool.snapshot();require(after["selectedOrderID"]==before["selectedOrderID"]&&after["selectedTrackID"]==before["selectedTrackID"]&&after["startOrder"]==before["startOrder"]&&after["orderCount"]==before["orderCount"]&&!after["error"].get<std::string>().empty(),"Malformed response partially replaced matrix state");
  f.intercept=[&](std::string,Json params){const auto oldState=f.state;auto stale=f.matrix(params);f.state["revision"]="during-read";f.tool.update(f.state);return Json{{"state",oldState},{"result",std::move(stale)}};};f.tool.refresh();require(f.tool.snapshot()["revision"]=="during-read"&&!f.tool.snapshot()["fresh"].get<bool>()&&!f.tool.snapshot()["pending"].get<bool>(),"Stale read completion replaced a newer revision");
}
void failedReadBackpressure(Owner &owner){
  Fixture f(owner.window);f.tool.open(f.state);const auto source=f.tool.snapshot();const auto first=f.requests.size();f.tool.open(f.state);f.postedRefreshes();require(f.requests.size()==first,"Unchanged visible reopening queried the worker");
  f.state["revision"]="updated";f.tool.open(f.state);const auto updated=f.requests.size();require(updated==first+1,"Changed visible opening did not read exactly once");f.postedRefreshes();require(f.requests.size()==updated,"Visible reopen left a duplicate queued worker read");
  f.intercept=[](std::string,Json)->Json{throw ScreamSeq::Api::ApiError(-32003,"Matrix response exceeds transport limit; request a smaller page");};f.state["revision"]="capacity-error";f.tool.update(f.state);f.postedRefreshes();const auto failed=f.requests.size();require(failed==updated+1&&!f.tool.snapshot()["fresh"].get<bool>()&&!f.tool.snapshot()["error"].get<std::string>().empty(),"Read capacity failure was not retained");
  for(int i=0;i<12;++i){f.tool.update(f.state);f.postedRefreshes();f.tool.open(f.state);f.postedRefreshes();}require(f.requests.size()==failed,"Persistent read failure retried on unchanged state or reopen");f.click(8406);f.postedRefreshes();require(f.requests.size()==failed+1,"Explicit Refresh did not permit exactly one retry");
  f.state["busy"]=true;f.tool.update(f.state);f.postedRefreshes();f.state["busy"]=false;f.tool.update(f.state);f.postedRefreshes();require(f.requests.size()==failed+1,"Busy transition retried the same failed read context");
  f.state["revision"]="next-revision";f.tool.update(f.state);f.postedRefreshes();require(f.requests.size()==failed+2,"New revision did not permit one automatic retry");f.intercept={};f.tool.update(f.state);f.postedRefreshes();require(f.requests.size()==failed+2,"Observer update silently retried after the external error cleared");f.click(8406);f.postedRefreshes();require(f.requests.size()==failed+3&&f.tool.snapshot()["fresh"].get<bool>(),"Explicit Refresh did not recover the retained page");
  const auto intact=f.tool.snapshot();for(bool shortTracks:{false,true}){f.intercept=[&](std::string,Json params){auto data=f.matrix(params);if(shortTracks)data["tracks"].erase(data["tracks"].end()-1);else data["orders"].erase(data["orders"].end()-1);return Json{{"state",f.state},{"result",std::move(data)}};};f.click(8406);const auto rejected=f.tool.snapshot();require(!rejected["error"].get<std::string>().empty()&&rejected["orderCount"]==intact["orderCount"]&&rejected["trackCount"]==intact["trackCount"]&&rejected["selectedOrderID"]==intact["selectedOrderID"],"Underfilled non-tail matrix response replaced retained page");}
  require(f.tool.snapshot()["selectedOrderID"]==source["selectedOrderID"],"Failed/recovered reads redirected selection");
}
void minimumIdentityLabels(Owner &owner){
  Fixture f(owner.window);const std::string longName=std::string(400,'x')+" / café / 旋律 🎵";
  f.intercept=[&](std::string method,Json params){require(method=="arrangement.matrix","Label fixture submitted a musical edit");auto data=f.matrix(params);for(auto &order:data["orders"]){order["name"]=longName;if(order["rows"]!=0)order["patternName"]=longName;}for(auto &track:data["tracks"])track["name"]=longName;return Json{{"state",f.state},{"result",std::move(data)}};};
  f.tool.open(f.state);MINMAXINFO minimum{};SendMessageW(f.tool.window(),WM_GETMINMAXINFO,0,reinterpret_cast<LPARAM>(&minimum));require(SetWindowPos(f.tool.window(),nullptr,0,0,minimum.ptMinTrackSize.x,minimum.ptMinTrackSize.y,SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE),"Resize long-name matrix fixture");
  const auto prefixFits=[&](int id,const std::wstring &prefix){const auto field=f.control(id);const int length=GetWindowTextLengthW(field);std::wstring text(size_t(length)+1,L'\0');GetWindowTextW(field,text.data(),length+1);text.resize(size_t(length));require(text.starts_with(prefix),"Long names hid or reordered block identity/density");require(text.size()>400,"Long native label fixture was unexpectedly shortened");RECT rect{};GetClientRect(field,&rect);const auto dc=GetDC(field);require(dc,"Read native label font metrics");const auto font=reinterpret_cast<HFONT>(SendMessageW(field,WM_GETFONT,0,0));const auto old=SelectObject(dc,font);SIZE size{};const auto measured=GetTextExtentPoint32W(dc,prefix.c_str(),int(prefix.size()),&size);SelectObject(dc,old);ReleaseDC(field,dc);require(measured&&size.cx<rect.right-4,"Block identity/density prefix is clipped at minimum width");};
  f.select(0,12);prefixFits(8502,L"Order 0 · Track 12 · P0 · tracker 1 / precise 1 / FX 1 · ");f.click(8408);const auto captured=f.tool.snapshot()["copied"];f.select(4,1);prefixFits(8502,L"Order 4 · Track 1 · P0 · tracker 1 / precise 1 / FX 1 · ");prefixFits(8503,L"Copied · Order 0 · Track 12 · P0 · ");
  f.state["revision"]="names-changed";f.tool.update(f.state);prefixFits(8503,L"STALE COPY · Order 0 · Track 12 · P0 · ");require(f.tool.snapshot()["copied"]["label"]==captured["label"]&&f.tool.snapshot()["copied"]["revision"]==captured["revision"]&&f.writeCount==0,"Label update rebased or mutated the captured copy");
}
}
int main(){try{SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);ScreamSeq::Tests::runPrivateGui(L"ScreamSeqMatrixTest",[]{Owner owner;densityAndKeyboard(owner);retainedCopyAndStale(owner);pagingRetentionAndBounds(owner);pumpedRequestsAndInvalidData(owner);failedReadBackpressure(owner);minimumIdentityLabels(owner);owner.close();});std::cout<<"PASS matrix retained pages, stable coordinates, native density accessibility, keyboard, captured-copy guards, pumped completion, bounded minimum, theme refresh, failed-read backpressure and visible long-name identity prefixes\n";return 0;}catch(const std::exception &e){std::cerr<<e.what()<<'\n';return 1;}}
