# Include BEFORE editor/hosted, then call screamseq_windows_vst3_target(TrackerHosted).
get_filename_component(SCREAMSEQ_VST3_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(SCREAMSEQ_VST3_SDK "${SCREAMSEQ_VST3_ROOT}/mac/ThirdParty/vst3")
set(SCREAMSEQ_VST3_SDK_SOURCES "${SCREAMSEQ_VST3_SDK}/pluginterfaces/base/funknown.cpp" "${SCREAMSEQ_VST3_SDK}/pluginterfaces/base/coreiids.cpp" "${SCREAMSEQ_VST3_SDK}/vstinitiids.cpp")
set(TRACKER_HOSTED_BACKEND_SOURCES "${CMAKE_CURRENT_LIST_DIR}/WindowsVST3.cpp" "${CMAKE_CURRENT_LIST_DIR}/Registry.cpp" "${CMAKE_CURRENT_LIST_DIR}/Module.cpp" "${CMAKE_CURRENT_LIST_DIR}/Scanner.cpp")
function(screamseq_windows_vst3_target target)
 target_sources(${target} PRIVATE ${SCREAMSEQ_VST3_SDK_SOURCES} "${SCREAMSEQ_VST3_ROOT}/windows/Project/BinaryPlist.cpp")
 target_include_directories(${target} PRIVATE "${SCREAMSEQ_VST3_SDK}" "${SCREAMSEQ_VST3_ROOT}/include/nlohmann-json/include")
 target_link_libraries(${target} PRIVATE user32 ole32 bcrypt)
endfunction()
add_executable(ScreamSeqVST3Scanner "${CMAKE_CURRENT_LIST_DIR}/ScannerMain.cpp" "${CMAKE_CURRENT_LIST_DIR}/Module.cpp" ${SCREAMSEQ_VST3_SDK_SOURCES})
target_compile_features(ScreamSeqVST3Scanner PRIVATE cxx_std_20)
target_compile_definitions(ScreamSeqVST3Scanner PRIVATE NOMINMAX UNICODE _UNICODE)
target_compile_options(ScreamSeqVST3Scanner PRIVATE /utf-8)
target_include_directories(ScreamSeqVST3Scanner PRIVATE "${SCREAMSEQ_VST3_SDK}" "${SCREAMSEQ_VST3_ROOT}" "${SCREAMSEQ_VST3_ROOT}/include" "${SCREAMSEQ_VST3_ROOT}/include/nlohmann-json/include")
target_link_libraries(ScreamSeqVST3Scanner PRIVATE bcrypt ole32)
foreach(notice README.md LICENSE.txt REVISIONS.json)
 configure_file("${SCREAMSEQ_VST3_SDK}/${notice}" "${CMAKE_CURRENT_BINARY_DIR}/VST3-NOTICES/${notice}" COPYONLY)
endforeach()
configure_file("${SCREAMSEQ_VST3_SDK}/pluginterfaces/LICENSE.txt" "${CMAKE_CURRENT_BINARY_DIR}/VST3-NOTICES/INTERFACES-LICENSE.txt" COPYONLY)
configure_file("${CMAKE_CURRENT_LIST_DIR}/README.md" "${CMAKE_CURRENT_BINARY_DIR}/VST3-NOTICES/Windows-provider.md" COPYONLY)
add_custom_command(TARGET ScreamSeqVST3Scanner POST_BUILD
 COMMAND "${CMAKE_COMMAND}" -E copy_directory "${CMAKE_CURRENT_BINARY_DIR}/VST3-NOTICES" "$<TARGET_FILE_DIR:ScreamSeqVST3Scanner>/VST3-NOTICES")
