#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
tracker_build="${SCREAMSEQ_BUILD_DIR:-${RESONANCE_BUILD_DIR:-$PWD/bin/mac-native}}"
mkdir -p "$tracker_build"
xcrun swiftc -swift-version 5 -target "$(uname -m)-apple-macosx14.0" mac/App/GraphCommandsEditor.swift mac/App/GraphPatternLanes.swift mac/App/GraphPluginControls.swift mac/App/SignalSongOverview.swift mac/App/SignalConnections.swift mac/App/SignalInstruments.swift mac/App/GraphEnvelopeEditor.swift mac/App/SignalCanvas.swift mac/App/SignalGraphEditor.swift mac/Tests/SignalGraphInterfaceTests.swift mac/App/DockWorkspace.swift mac/App/CommandSequences.swift mac/App/CommandPalette.swift mac/Tests/WorkspaceInterfaceTests.swift mac/App/SampleMultisample.swift mac/App/MultisampleImport.swift mac/App/SampleLibrary.swift mac/App/SampleAudition.swift mac/App/SampleBrowser.swift mac/Tests/SampleBrowserInterfaceTests.swift mac/App/RecoveryStore.swift mac/App/RecoveryBrowser.swift mac/Tests/RecoveryInterfaceTests.swift mac/App/Theme.swift mac/App/EditorNavigation.swift mac/App/PatternCommands.swift mac/App/PreciseNotes.swift mac/Tests/PreciseNotesInterfaceTests.swift mac/App/PatternPerformance.swift mac/Tests/PatternPerformanceInterfaceTests.swift mac/App/NoteTracks.swift mac/App/PluginBrowser.swift mac/App/KeyboardSettings.swift mac/App/PatternView.swift \
  mac/App/AssetEditors.swift mac/App/WaveformView.swift mac/App/SampleWaveformEditor.swift mac/App/SampleSnapEditor.swift mac/App/SampleLoopEditor.swift mac/App/SampleCrossfadeEditor.swift mac/App/SampleClipboardEditor.swift mac/App/OrderEditor.swift mac/App/PluginEditor.swift mac/App/PatternTools.swift mac/App/ArrangementMatrix.swift mac/App/PatternAutomation.swift mac/App/FormulaWorkbench.swift mac/App/EnvelopeBank.swift mac/App/PatternAutomationTools.swift mac/App/AutomationTarget.swift mac/App/MixerStrips.swift mac/App/MixerEditor.swift mac/App/PluginPorts.swift mac/App/SidechainEditor.swift mac/Tests/InterfaceTests.swift mac/Tests/EnvelopeBankInterfaceTests.swift mac/Tests/NavigationInterfaceTests.swift mac/Tests/NoteTracksInterfaceTests.swift mac/Tests/PluginBrowserInterfaceTests.swift mac/Tests/PatternCommandsInterfaceTests.swift mac/Tests/AutomationToolsInterfaceTests.swift mac/Tests/AutomationTargetInterfaceTests.swift mac/Tests/SampleSnapInterfaceTests.swift mac/Tests/SampleLoopInterfaceTests.swift mac/Tests/SampleCrossfadeInterfaceTests.swift \
  mac/App/InstrumentEnvelopeToolsEditor.swift mac/Tests/InstrumentEnvelopeInterfaceTests.swift mac/App/PluginProgramsEditor.swift mac/Tests/PluginProgramsInterfaceTests.swift mac/App/PluginInstrumentsEditor.swift mac/Tests/PluginInstrumentsInterfaceTests.swift mac/App/SongTimingEditor.swift mac/Tests/SongTimingInterfaceTests.swift mac/App/PluginPresetWorkflow.swift mac/Tests/PluginPresetInterfaceTests.swift mac/Tests/MixerStripsInterfaceTests.swift -framework AppKit -framework MetalKit -o "$tracker_build/interface-tests"
"$tracker_build/interface-tests" "$@"
