#import "../Bridge/TrackerSession.h"
#include "editor/TrackerDocument.hpp"
#include "editor/InstrumentEnvelopeTools.hpp"
#include <iostream>
using namespace Tracker;using namespace OpenMPT;
static void check(bool b,const char *why){if(!b)throw std::runtime_error(why);}
int main(){@autoreleasepool{try{
 NSString *folder=[NSTemporaryDirectory() stringByAppendingPathComponent:NSUUID.UUID.UUIDString];[NSFileManager.defaultManager createDirectoryAtPath:folder withIntermediateDirectories:YES attributes:nil error:nil];setenv("RESONANCE_AUTOMATION_TEST_DIRECTORY",folder.UTF8String,1);
 Document fixture(MOD_TYPE_IT);fixture.transaction([](CSoundFile &s){s.m_nInstruments=2;s.Instruments[1]=new ModInstrument(1);s.Instruments[2]=new ModInstrument(1);s.m_nSamples=1;auto &sample=s.GetSample(1);sample.Initialize();sample.nLength=64;sample.nLoopStart=0;sample.nLoopEnd=64;sample.uFlags.set(CHN_16BIT|CHN_LOOP);if(!sample.AllocateSample())throw std::bad_alloc();for(int i=0;i<64;++i)sample.sample16()[i]=int16_t((i%16-8)*1600);sample.PrecomputeLoops(s,false);auto &e=s.Instruments[1]->VolEnv;e.push_back(0,0);e.push_back(4,64);e.push_back(8,32);e.push_back(12,0);e.dwFlags.set(ENV_ENABLED|ENV_SUSTAIN);e.nSustainStart=e.nSustainEnd=1;auto &note=*s.Patterns[0].GetpModCommand(0,0);note.note=61;note.instr=1;s.Patterns[0].GetpModCommand(8,0)->note=NOTE_KEYOFF;});
 NSString *source=[folder stringByAppendingPathComponent:@"source.it"];fixture.save(source.UTF8String);TrackerSession *session=[TrackerSession new];NSError *error=nil;check([session openPath:source error:&error],"Open instrument fixture");
 auto call=[&](NSString *method,NSDictionary *params,bool write=false)->NSDictionary *{auto p=[params mutableCopy];if(write)p[@"expectedRevision"]=session.automationRevision;NSError *e=nil;auto r=[session automationMethod:method params:p error:&e];if(!r)throw std::runtime_error([[NSString stringWithFormat:@"%@: %@",method,e.localizedDescription] UTF8String]);return r;};
 auto reject=[&](NSString *method,NSDictionary *params){auto p=[params mutableCopy];if(!p[@"expectedRevision"])p[@"expectedRevision"]=session.automationRevision;NSString *revision=session.automationRevision;auto before=[session serializedData];check(![session automationMethod:method params:p error:&error],"Invalid bank write accepted");check([revision isEqual:session.automationRevision]&&[before isEqual:[session serializedData]],"Rejected edit changed song");};
 auto invalidParams=@{@"expectedRevision":session.automationRevision,@"name":@"Invalid",@"shape":@{@"span":@1,@"points":@[]},@"dryRun":@YES};check(![session automationMethod:@"envelope.bank.save" params:invalidParams error:&error]&&error.code==-32602,"Malformed bank shapes need a validation error");
 auto bank=[&](){return call(@"envelope.bank.list",@{})[@"data"];};
 auto snapshot=[session snapshot:0];NSString *instrument=snapshot[@"instruments"][0][@"id"],*second=snapshot[@"instruments"][1][@"id"];
 NSDictionary *it=@{@"kind":@"volume",@"instrument":instrument},*it2=@{@"kind":@"volume",@"instrument":second};
 NSDictionary *saved=@{@"name":@"Pluck",@"target":it};NSString *revision=session.automationRevision;auto dry=[saved mutableCopy];dry[@"dryRun"]=@YES;call(@"envelope.bank.save",dry,true);check([revision isEqual:session.automationRevision]&&[bank()[@"entries"] count]==0,"Dry run mutated bank");
 NSString *master=call(@"envelope.bank.save",saved,true)[@"data"][@"id"];auto shape=bank()[@"entries"][0][@"shape"];
 check([shape[@"points"] count]==4,"Captured instrument points missing");
 NSDictionary *apply=@{@"template":master,@"target":it,@"linked":@YES};call(@"envelope.bank.apply",apply,true);check([bank()[@"links"] count]==1,"Linked instrument missing");
 auto original=call(@"instrument.envelope.get",@{@"instrument":instrument,@"envelope":@"volume"})[@"data"];
 check([original[@"points"] isEqual:@[@[@0,@0],@[@4,@64],@[@8,@32],@[@12,@0]]]&&[original[@"sustainPoint"] intValue]==1,"Instrument capture/bake moved points or markers");
 revision=session.automationRevision;call(@"envelope.bank.apply",apply,true);check([revision isEqual:session.automationRevision],"Identical apply created undo");
 call(@"envelope.bank.apply",@{@"template":master,@"target":it2,@"linked":@NO},true);auto independent=call(@"instrument.envelope.get",@{@"instrument":second,@"envelope":@"volume"})[@"data"];
 NSString *graph=call(@"graph.create",@{@"name":@"Bank test"},true)[@"data"][@"graph"];
 NSString *node=call(@"graph.node.add",@{@"graph":graph,@"kind":@"automation"},true)[@"data"][@"node"];
 NSDictionary *gt=@{@"kind":@"graph",@"graph":graph,@"node":node,@"pattern":@0};call(@"envelope.bank.apply",@{@"template":master,@"target":gt,@"linked":@YES},true);
 auto graphBefore=call(@"graph.automation.get",@{@"graph":graph,@"node":node,@"pattern":@0})[@"data"];
 auto modified=[shape mutableCopy];NSMutableArray *points=[NSMutableArray array];for(NSDictionary *p in shape[@"points"]){auto p2=[p mutableCopy];p2[@"value"]=@(1-[p[@"value"] doubleValue]);[points addObject:p2];}modified[@"points"]=points;
 NSDictionary *update=@{@"id":master,@"name":@"Inverse pluck",@"shape":modified};dry=[update mutableCopy];dry[@"dryRun"]=@YES;revision=session.automationRevision;call(@"envelope.bank.save",dry,true);check([revision isEqual:session.automationRevision],"Multi-target dry run changed song");call(@"envelope.bank.save",update,true);
 auto linkedAfter=call(@"instrument.envelope.get",@{@"instrument":instrument,@"envelope":@"volume"})[@"data"];
 check([linkedAfter[@"points"][0][1] intValue]==64,"Master update did not reach linked instrument");check([independent isEqual:call(@"instrument.envelope.get",@{@"instrument":second,@"envelope":@"volume"})[@"data"]],"Independent copy changed with master");check([call(@"graph.automation.get",@{@"graph":graph,@"node":node,@"pattern":@0})[@"data"][@"points"][0][@"value"] doubleValue]==1,"Master did not update linked graph");
 call(@"history.undo",@{@"domain":@"document"},true);check([original isEqual:call(@"instrument.envelope.get",@{@"instrument":instrument,@"envelope":@"volume"})[@"data"]]&&[graphBefore isEqual:call(@"graph.automation.get",@{@"graph":graph,@"node":node,@"pattern":@0})[@"data"]],"One Undo failed to restore master and linked users");call(@"history.redo",@{@"domain":@"document"},true);
 reject(@"envelope.bank.save",@{@"id":master,@"name":@"Stale",@"shape":shape,@"expectedRevision":revision});reject(@"envelope.bank.remove",@{@"id":master});reject(@"instrument.patch",@{@"instrument":@1,@"values":@{@"envelope":@0,@"points":@[@[@0,@1],@[@1,@2]]}});reject(@"graph.automation.set",@{@"graph":graph,@"node":node,@"pattern":@0,@"points":@[@{@"position":@0,@"value":@0}]});
 auto catalogue=call(@"envelope.catalogue.list",@{})[@"data"];NSString *catalogueID=call(@"envelope.catalogue.publish",@{@"template":master,@"expectedCatalogueRevision":catalogue[@"revision"]},true)[@"data"][@"id"];catalogue=call(@"envelope.catalogue.list",@{})[@"data"];auto catalogueSnapshot=catalogue;
 call(@"envelope.bank.save",@{@"id":master,@"name":@"Changed in song only",@"shape":shape},true);check([catalogueSnapshot isEqual:call(@"envelope.catalogue.list",@{})[@"data"]],"Master change leaked into catalogue");
 auto imported=call(@"envelope.catalogue.import",@{@"catalogueID":catalogueID,@"expectedCatalogueRevision":catalogue[@"revision"]},true)[@"data"][@"id"];check(![master isEqual:imported]&&[bank()[@"entries"] count]==2,"Catalogue import reused song identity");
 call(@"envelope.catalogue.publish",@{@"template":master,@"catalogueID":catalogueID,@"expectedCatalogueRevision":catalogue[@"revision"]},true);check([bank()[@"entries"][1][@"name"] isEqual:@"Inverse pluck"],"Catalogue overwrite mutated imported template");reject(@"envelope.catalogue.publish",@{@"template":master,@"catalogueID":catalogueID,@"expectedCatalogueRevision":catalogue[@"revision"]});
 auto expected=bank();NSString *project=[folder stringByAppendingPathComponent:@"bank.screamseq"];if(![session savePath:project error:&error]||![session openPath:project error:&error])throw std::runtime_error(error.localizedDescription.UTF8String);check([expected isEqual:bank()],"Native bank roundtrip lost templates or links");
 // Linked metadata must be acoustically transparent; compare every PCM frame.
 NSString *wav=[folder stringByAppendingPathComponent:@"bank.wav"];check([TrackerSession exportData:[session serializedData] path:wav error:&error],"Render linked envelope");Renderer reference(fixture.snapshotData(),48000);NSData *audio=[NSData dataWithContentsOfFile:wav];size_t offset=44;double energy=0;std::array<float,1024> pcm{};while(auto count=reference.render(pcm.data(),512)){check(offset+count*8<=audio.length,"Rendered audio is truncated");check(!std::memcmp(static_cast<const char *>(audio.bytes)+offset,pcm.data(),count*8),"Bank changed playback PCM");for(size_t i=0;i<count*2;++i)energy+=std::abs(pcm[i]);offset+=count*8;}check(offset==audio.length&&energy>1,"Rendered audio is complete and audible");
 call(@"envelope.bank.unlink",@{@"target":it},true);call(@"envelope.bank.unlink",@{@"target":gt},true);check([bank()[@"links"] count]==0,"Unlink left dangling users");call(@"envelope.bank.remove",@{@"id":master},true);
 call(@"plugin.add",@{@"descriptor":[session builtInPlugins][0]},true);auto plugin=[session snapshot:0][@"nativePlugins"][0][@"instanceID"];
 NSDictionary *pt=@{@"kind":@"parameter",@"pattern":@0,@"plugin":plugin,@"parameter":@1};call(@"envelope.bank.apply",@{@"template":imported,@"target":pt,@"linked":@YES},true);
 auto lane=call(@"automation.pattern.get",@{@"pattern":@0})[@"data"][@"lanes"][0];check([lane[@"points"][0][@"value"] doubleValue]==1,"Bank did not create parameter lane");
 reject(@"automation.pattern.set",@{@"pattern":@0,@"plugin":plugin,@"parameter":@1,@"points":@[@{@"position":@0,@"value":@0.5}]});
 call(@"envelope.bank.save",@{@"id":imported,@"name":@"Linked parameter",@"shape":shape},true);check([call(@"automation.pattern.get",@{@"pattern":@0})[@"data"][@"lanes"][0][@"points"][0][@"value"] doubleValue]==0,"Parameter link did not follow master");
 call(@"automation.pattern.remove",@{@"lane":lane[@"id"]},true);check([bank()[@"links"] count]==0,"Deleting parameter lane did not prune link");
 // Resizing must refit even a template whose first point was outside the new extent.
 Document resize(MOD_TYPE_IT);resize.annotate([](NativeSong &n){EnvelopeShape shape;shape.span=64*256;shape.points={{63*256,.2},{64*256-1,.8}};auto master=n.makeEntity().id,lane=n.makeEntity().id;n.envelopeBank.push_back({master,"Late",shape});n.automation.push_back({lane,n.patterns.at(0).id,"fixture",1,true,shape.points});n.envelopeLinks.push_back({{EnvelopeTargetKind::Parameter,lane,0},master,shape.span});});
 resize.transaction([](CSoundFile &s){s.Patterns[0].Resize(32);});check(resize.native().envelopeLinks.size()==1&&resize.native().automation[0].points.back().position==32*256-1,"Pattern shrink lost late linked points");resize.undo();check(resize.native().envelopeLinks[0].span==64*256,"Resize undo did not restore linked span");
 resize.addPattern(32,true,0);check(resize.native().envelopeLinks.size()==2&&resize.native().envelopeLinks[0].target.owner!=resize.native().envelopeLinks[1].target.owner,"Cloning pattern reused linked target identity");
 resize.transaction([](CSoundFile &s){s.Patterns.Remove(0);});check(resize.native().envelopeLinks.size()==1,"Deleting pattern did not prune its links");
 EnvelopeShape difficult;difficult.span=256;difficult.points={{0,0,AutomationCurve::Scripted,CurveFormula("0.5+0.5*sin(t*1000)")}};bool refused=false;try{bakeInstrumentEnvelope(difficult,256,25);}catch(const std::invalid_argument &){refused=true;}check(refused,"Unrepresentable instrument curve silently degraded");
 check([[TrackerSession formulaReference][@"symbols"] count]>40,"Reference symbol catalogue missing");[NSFileManager.defaultManager removeItemAtPath:folder error:nil];std::cout<<"PASS envelope banks: guarded atomic edits, native markers, graph links, independent copies, one-step Undo/Redo, stale rejection, two-tier catalogue isolation, save/reopen and complete PCM equality\n";return 0;
}catch(const std::exception &e){std::cerr<<e.what()<<'\n';return 1;}}}
