#import "../Bridge/TrackerSession.h"
#include "../Audio/AudioUnitHost.hpp"
#include "../Bridge/SignalTelemetry.hpp"
#include "editor/TrackerDocument.hpp"
#include <iostream>
using namespace Tracker;
static void check(bool b,const char *message){if(!b)throw std::runtime_error(message);}

#include "GraphEditingSessionChecks.inc"
#include "GraphStageSessionChecks.inc"
#include "SignalTelemetrySessionChecks.inc"
int main(){@autoreleasepool{try{
  signalTelemetryProjectionChecks();
  TrackerSession *session=[TrackerSession new];NSError *error=nil;
  check([[session signalTelemetry] isEqual:[session songSignalTelemetry]],"Stopped root projection must retain the full telemetry envelope and empty-port semantics");
  auto call=[&](NSString *method,NSDictionary *parameters,bool write=false)->NSDictionary *{auto p=[parameters mutableCopy];if(write)p[@"expectedRevision"]=session.automationRevision;auto response=[session automationMethod:method params:p error:&error];if(!response)throw std::runtime_error(std::string(method.UTF8String)+": "+error.localizedDescription.UTF8String);return response;};
  auto data=[&](){return call(@"graph.get",@{})[@"data"];};
  auto empty=data();NSString *revision=session.automationRevision;
  auto signals=call(@"graph.signal.get",@{});
  check(![signals[@"changed"] boolValue] && ![signals[@"data"][@"active"] boolValue] && [revision isEqual:session.automationRevision],"Signal observation is a read and explicitly distinguishes stopped transport");
  check([signals[@"data"][@"freshnessFrames"] integerValue]==4096,"Signal API declares its bounded audio-clock freshness window");
  check([call(@"graph.listen.get",@{})[@"data"][@"available"] boolValue],"Normal mix remains available without a prepared engine");
  NSError *signalError=nil;
  check(![session automationMethod:@"graph.signal.clear" params:@{@"port":@"missing/out/0",@"expectedRevision":revision} error:&signalError] && [revision isEqual:session.automationRevision],"An unknown observation target cannot alter the song");
  auto scope=call(@"graph.scope.get",@{@"spectrum":@YES});check(scope[@"data"][@"port"]==NSNull.null && [scope[@"data"][@"frames"] integerValue]==0,"No prepared scope is explicitly empty");
  check(call(@"graph.listen.get",@{})[@"data"][@"port"]==NSNull.null,"A new session has no monitor override");
  check(![call(@"graph.listen.set",@{@"port":NSNull.null},true)[@"changed"] boolValue],"Stop listening is session state without Undo");
  check(![session automationMethod:@"graph.listen.set" params:@{@"port":@"missing/out/0",@"expectedRevision":revision} error:&signalError] && [revision isEqual:session.automationRevision],"Unknown monitor port is rejected unchanged");
  check(![call(@"graph.scope.watch",@{@"port":NSNull.null},true)[@"changed"] boolValue],"Stopping scope capture creates no song edit or Undo");
  check(![session automationMethod:@"graph.scope.watch" params:@{@"port":@"missing/out/0",@"expectedRevision":revision} error:&signalError] && [revision isEqual:session.automationRevision],"Unknown scope port is rejected unchanged");
  call(@"graph.create",@{@"name":@"Echo",@"dryRun":@YES},true);check([revision isEqual:session.automationRevision]&&[empty isEqual:data()],"Graph preview mutates document");
  NSString *graph=call(@"graph.create",@{@"name":@"Echo"},true)[@"data"][@"graph"];
  NSString *node=call(@"graph.node.add",@{@"graph":graph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"}},true)[@"data"][@"node"];
  NSMutableDictionary *definition=[data()[@"library"][0] mutableCopy];NSArray *nodes=definition[@"nodes"];
  definition[@"audio"]=@[@{@"source":nodes[0][@"id"],@"target":node},@{@"source":node,@"target":nodes[1][@"id"]}];
  call(@"graph.update",@{@"definition":definition},true);
  auto metadata=call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"];
  check([metadata[@"parameters"] count]>=2&&[metadata[@"buses"] count]>=2,"Graph recipe exposes parameters and ports");
  revision=session.automationRevision;
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-6)}],@"dryRun":@YES},true);
  check([revision isEqual:session.automationRevision],"Plugin recipe preview committed");
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-6)}]},true);
  auto parameters=call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"][@"parameters"];
  check([parameters[1][@"value"] doubleValue]==-6,"Graph plugin parameter did not persist in recipe");
  check([parameters[1][@"manualValue"] doubleValue]==-6&&parameters[1][@"effectiveValue"]==NSNull.null&&[parameters[1][@"valueRole"] isEqual:@"manual-template"],"Recipe reads identify their editable manual template and never invent one effective value for all copies");
  const auto parameterState=data();revision=session.automationRevision;
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-6)}]},true);
  check([revision isEqual:session.automationRevision],"Identical graph parameter write must preserve history");
  call(@"history.undo",@{},true);check([call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"][@"parameters"][1][@"value"] doubleValue]==0,"Undo removes an explicit baseline and restores preset value");
  call(@"history.redo",@{},true);check([parameterState isEqual:data()],"Redo restores exact explicit graph baseline");
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-9)}],@"gesture":@"drag-one"},true);
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-12)}],@"gesture":@"drag-one"},true);
  call(@"history.undo",@{},true);check([parameterState isEqual:data()],"One Undo restores the start of a graph parameter drag");
  call(@"history.redo",@{},true);auto dragState=data();
  call(@"graph.layout.set",@{@"positions":@[@{@"node":@"gesture-break",@"x":@1,@"y":@2}]},true);auto interleavedState=data();
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-15)}],@"gesture":@"drag-one"},true);
  call(@"history.undo",@{},true);check([interleavedState isEqual:data()],"Intervening layout edits break graph drag coalescing");
  call(@"history.undo",@{},true);check([dragState isEqual:data()],"Interleaved layout retains its own Undo");
  call(@"history.undo",@{},true);check([parameterState isEqual:data()],"Earlier drag remains one Undo after an interleaved edit");
  call(@"graph.layout.set",@{@"positions":@[@{@"node":@"test-node",@"x":@125,@"y":@250}]},true);
  check([data()[@"layout"] count]==1,"Graph layout missing from API");
  call(@"mixer.enable",@{},true);NSString *target=data()[@"mixer"][@"buses"][0][@"id"];
  call(@"graph.assign",@{@"target":target,@"graph":graph,@"amount":@.4,@"wet":@.7},true);
  definition=[data()[@"library"][0] mutableCopy];NSMutableArray *audio=[definition[@"audio"] mutableCopy];[audio addObject:@{@"source":nodes[0][@"id"],@"target":nodes[1][@"id"],@"output":@1,@"input":@1}];definition[@"audio"]=audio;call(@"graph.update",@{@"definition":definition},true);
  NSString *side=data()[@"mixer"][@"buses"][1][@"id"],*master=[data()[@"mixer"][@"buses"] lastObject][@"id"];
  call(@"graph.routes.set",@{@"inputs":@[@{@"source":side,@"target":target,@"input":@1}],@"outputs":@[@{@"source":target,@"target":master,@"output":@1}]},true);
  call(@"graph.commands.set",@{@"pattern":@0,@"lanes":@[@{@"target":target,@"count":@2}],@"commands":@[@{@"target":target,@"graph":graph,@"kind":@"start",@"position":@32768,@"amount":@.2},@{@"target":target,@"kind":@"clear",@"position":@65536}]},true);
  NSString *automation=call(@"graph.node.add",@{@"graph":graph,@"kind":@"automation",@"name":@"Drawn motion"},true)[@"data"][@"node"];
  auto curveData=[&](){return call(@"graph.automation.get",@{@"graph":graph,@"node":automation,@"pattern":@0})[@"data"];};
  check([curveData()[@"points"] count]==0,"New graph curve must be empty");revision=session.automationRevision;
  NSDictionary *curve=@{@"graph":graph,@"node":automation,@"pattern":@0,@"points":@[@{@"position":@0,@"value":@0,@"curve":@"scripted",@"formula":@"mix(start,end,t^2)"},@{@"position":@255,@"value":@1,@"curve":@"step"}]};
  NSMutableDictionary *preview=[curve mutableCopy];preview[@"dryRun"]=@YES;call(@"graph.automation.set",preview,true);check([revision isEqual:session.automationRevision],"Graph curve preview mutates song");
  call(@"graph.automation.set",curve,true);check([curveData()[@"points"] count]==2,"Graph curve write missing");revision=session.automationRevision;call(@"graph.automation.set",curve,true);check([revision isEqual:session.automationRevision],"Identical graph curve creates Undo history");
  call(@"history.undo",@{@"domain":@"document"},true);check([curveData()[@"points"] count]==0,"Graph curve undo failed");call(@"history.redo",@{@"domain":@"document"},true);
  const auto instrument=[session addInstrument:1 error:&error];check(instrument>0,"Create instrument graph target");
  call(@"graph.instrument.assign",@{@"instrument":@(instrument),@"graph":graph,@"amount":@.3,@"wet":@.6},true);
  check([data()[@"instrumentAssignments"] count]==1,"Instrument graph assignment is missing");
  call(@"history.undo",@{@"domain":@"document"},true);check([data()[@"instrumentAssignments"] count]==0,"Instrument assignment undo failed");call(@"history.redo",@{@"domain":@"document"},true);
  auto modulatedDefinition=[data()[@"library"][0] mutableCopy];
  auto graphParameters=call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"][@"parameters"];
  NSDictionary *gainParameter=nil;for(NSDictionary *parameter in graphParameters)if([parameter[@"id"] integerValue]==1)gainParameter=parameter;
  modulatedDefinition[@"modulation"]=@[@{@"source":automation,@"target":node,@"parameter":@1,@"base":@.25,@"minimum":@0,@"maximum":@0}];
  call(@"graph.update",@{@"definition":modulatedDefinition},true);
  const double base=[gainParameter[@"min"] doubleValue]+.25*([gainParameter[@"max"] doubleValue]-[gainParameter[@"min"] doubleValue]);
  graphParameters=call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"][@"parameters"];
  for(NSDictionary *parameter in graphParameters)if([parameter[@"id"] integerValue]==1)check(std::abs([parameter[@"value"] doubleValue]-base)<1e-5,"Graph inspector reports the modulation baseline in native units");
  revision=session.automationRevision;call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(base)}]},true);
  check([revision isEqual:session.automationRevision],"Setting the existing modulation baseline creates no spurious Undo");
  call(@"history.undo",@{},true);
  auto expected=data();revision=session.automationRevision;
  auto reject=[&](NSString *method,NSDictionary *parameters){auto p=[parameters mutableCopy];p[@"expectedRevision"]=session.automationRevision;NSError *failure=nil;check(![session automationMethod:method params:p error:&failure],"Invalid graph edit accepted");check([revision isEqual:session.automationRevision]&&[expected isEqual:data()],"Rejected graph edit partially committed");};
  reject(@"graph.automation.set",@{@"graph":graph,@"node":automation,@"pattern":@0,@"points":@[@{@"position":@0,@"value":@0},@{@"position":@0,@"value":@1}]});
  reject(@"graph.automation.set",@{@"graph":graph,@"node":node,@"pattern":@0,@"points":@[]});
  reject(@"graph.node.add",@{@"graph":graph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"},@"connect":@{@"node":node,@"port":@0,@"output":@NO,@"quantized":@NO}});
  reject(@"graph.routes.set",@{@"inputs":@[@{@"source":master,@"target":target,@"input":@1}]});
  reject(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@999}]});
  reject(@"graph.layout.set",@{@"positions":@[@{@"node":@"bad",@"x":@(-1),@"y":@0}]});
  reject(@"graph.remove",@{@"graph":graph});
  reject(@"graph.commands.set",@{@"pattern":@0,@"lanes":@[@{@"target":target,@"count":@0}]});
  definition=[expected[@"library"][0] mutableCopy];definition[@"audio"]=@[@{@"source":node,@"target":node}];reject(@"graph.update",@{@"definition":definition});
  call(@"history.undo",@{@"domain":@"document"},true);check([data()[@"instrumentAssignments"] count]==0,"Undo failed to remove instrument graph transaction");call(@"history.redo",@{@"domain":@"document"},true);check([expected isEqual:data()],"Redo lost graph identities or values");
  NSString *path=[NSTemporaryDirectory() stringByAppendingPathComponent:[NSUUID.UUID.UUIDString stringByAppendingString:@".screamseq"]];
  check([session savePath:path error:&error]&&[session openPath:path error:&error],"Graph project save/reload failed");check([expected isEqual:data()],"Graph project roundtrip lost data");
  call(@"graph.clone",@{@"graph":graph,@"name":@"Echo copy"},true);auto copied=data()[@"library"][1];check(![copied[@"id"] isEqual:graph]&&![copied[@"nodes"][0][@"id"] isEqual:expected[@"library"][0][@"nodes"][0][@"id"]],"Cloned graph reused identities");
  NSString *extra=call(@"graph.node.add",@{@"graph":graph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"}},true)[@"data"][@"node"];
  auto patchBefore=data();revision=session.automationRevision;
  NSDictionary *patch=@{@"graph":graph,@"nodes":@[extra],@"edge":@0,@"positions":@[@{@"node":extra,@"x":@325,@"y":@200}]};
  auto patchPreview=[patch mutableCopy];patchPreview[@"dryRun"]=@YES;call(@"graph.nodes.insert",patchPreview,true);
  check([revision isEqual:session.automationRevision]&&[patchBefore isEqual:data()],"Insertion dry-run must leave topology, layout and history unchanged");
  call(@"graph.nodes.insert",patch,true);auto patchAfter=data();
  check([patchAfter[@"library"][0][@"audio"] count]==[patchBefore[@"library"][0][@"audio"] count]+1,"Disconnected processor inserts on the selected wire");
  call(@"history.undo",@{@"domain":@"document"},true);check([patchBefore isEqual:data()],"One insertion Undo restores topology and position");
  call(@"history.redo",@{@"domain":@"document"},true);check([patchAfter isEqual:data()],"Insertion Redo restores exact wiring and layout");
  auto badPatch=[patch mutableCopy];badPatch[@"expectedRevision"]=session.automationRevision;badPatch[@"edge"]=@255;NSError *patchError=nil;
  check(![session automationMethod:@"graph.nodes.insert" params:badPatch error:&patchError]&&[patchAfter isEqual:data()],"An invalid insertion edge cannot move nodes or damage wiring");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[patchAfter isEqual:data()],"Inserted topology and layout persist with recipe state intact");
  auto detachPreview=call(@"graph.nodes.detach",@{@"graph":graph,@"nodes":@[extra],@"dryRun":@YES},true);
  check([detachPreview[@"data"][@"wouldChange"] boolValue]&&[patchAfter isEqual:data()],"Detach preview leaves processors and routes intact");
  call(@"graph.nodes.detach",@{@"graph":graph,@"nodes":@[extra],@"positions":@[@{@"node":extra,@"x":@600,@"y":@300}]},true);auto detached=data();
  check([detached[@"library"][0][@"audio"] count]+1==[patchAfter[@"library"][0][@"audio"] count],"Detach removes two boundary cables and adds exactly one bridge");
  call(@"history.undo",@{},true);check([patchAfter isEqual:data()],"Detach and move share one Undo");
  call(@"history.redo",@{},true);check([detached isEqual:data()],"Detach Redo retains layout and identities");
  call(@"history.undo",@{},true);
  call(@"graph.nodes.detach",@{@"graph":graph,@"nodes":@[extra],@"remove":@YES},true);
  check([data()[@"library"][0][@"nodes"] count]+1==[patchAfter[@"library"][0][@"nodes"] count],"Delete-and-heal removes only the selected effect");
  call(@"history.undo",@{},true);check([patchAfter isEqual:data()],"Delete-and-heal restores exact state in one Undo");
  auto addBefore=data();auto addRevision=session.automationRevision;
  NSDictionary *insertNew=@{@"graph":graph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"},@"insertEdge":@0,@"x":@510,@"y":@220};
  auto newPreview=[insertNew mutableCopy];newPreview[@"dryRun"]=@YES;call(@"graph.node.add",newPreview,true);
  check([addRevision isEqual:session.automationRevision]&&[addBefore isEqual:data()],"Add at edge dry-run changes no state or identity allocator");
  NSString *inserted=call(@"graph.node.add",insertNew,true)[@"data"][@"node"];
  auto addAfter=data(),oldEdge=addBefore[@"library"][0][@"audio"][0],newEdge=addAfter[@"library"][0][@"audio"][0];
  check([newEdge[@"source"] isEqual:inserted]&&[newEdge[@"target"] isEqual:oldEdge[@"target"]]&&[addAfter[@"library"][0][@"audio"] count]==[addBefore[@"library"][0][@"audio"] count]+1,"New processor splits precisely the selected cable");
  call(@"history.undo",@{},true);check([addBefore isEqual:data()],"One Undo restores cable and removes added node");
  call(@"history.redo",@{},true);check([addAfter isEqual:data()],"Add-and-connect Redo preserves identities");
  auto invalidAdd=[insertNew mutableCopy];invalidAdd[@"insertEdge"]=@255;invalidAdd[@"expectedRevision"]=session.automationRevision;NSError *addError=nil;
  check(![session automationMethod:@"graph.node.add" params:invalidAdd error:&addError]&&[addAfter isEqual:data()],"Invalid cable cannot leave an orphan plugin");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[addAfter isEqual:data()],"Add at cable survives save/reopen");
  auto connectBefore=data();
  NSDictionary *newSource=@{@"graph":graph,@"kind":@"lfo",@"connect":@{@"node":node,@"port":@1,@"output":@NO,@"modulation":@YES,@"base":@0.4}};
  auto source=call(@"graph.node.add",newSource,true)[@"data"][@"node"];
  auto connected=data();auto mod=[connected[@"library"][0][@"modulation"] lastObject];
  check([mod[@"source"] isEqual:source]&&[mod[@"target"] isEqual:node]&&[mod[@"minimum"] doubleValue]==0&&[mod[@"maximum"] doubleValue]==0&&[mod[@"base"] doubleValue]==0.4,"Creating a source from a parameter socket is atomic and initially silent");
  call(@"history.undo",@{},true);check([connectBefore isEqual:data()],"One Undo removes the source and cable together");
  NSDictionary *followerGesture=@{@"graph":graph,@"kind":@"follower",@"audioInput":@{@"node":nodes[0][@"id"],@"port":@0},@"connect":@{@"node":node,@"port":@1,@"output":@NO,@"modulation":@YES,@"base":@0.4}};
  auto followerPreview=[followerGesture mutableCopy];followerPreview[@"dryRun"]=@YES;auto followerRevision=session.automationRevision;
  call(@"graph.node.add",followerPreview,true);check([followerRevision isEqual:session.automationRevision]&&[connectBefore isEqual:data()],"Follower conversion preview leaves no node, wire or history");
  auto followerID=call(@"graph.node.add",followerGesture,true)[@"data"][@"node"];auto followerState=data();
  auto followerInput=[followerState[@"library"][0][@"audio"] lastObject],followerMod=[followerState[@"library"][0][@"modulation"] lastObject];
  check([followerInput[@"target"] isEqual:followerID]&&[followerInput[@"source"] isEqual:nodes[0][@"id"]]&&[followerMod[@"source"] isEqual:followerID]&&[followerMod[@"target"] isEqual:node]&&[followerMod[@"maximum"] doubleValue]==0,"Audio-to-parameter conversion preserves both exact endpoints at zero depth");
  call(@"history.undo",@{},true);check([connectBefore isEqual:data()],"One Undo removes follower and both wires");
  call(@"history.redo",@{},true);check([followerState isEqual:data()],"Follower redo preserves identities and endpoints");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[followerState isEqual:data()],"Follower conversion survives project reopen");
  call(@"graph.node.remove",@{@"graph":graph,@"node":followerID},true);
  auto rejectFollower=[&](NSDictionary *params){auto before=data();auto revision=session.automationRevision;auto guarded=[params mutableCopy];guarded[@"expectedRevision"]=revision;NSError *failure=nil;check(![session automationMethod:@"graph.node.add" params:guarded error:&failure]&&[revision isEqual:session.automationRevision]&&[before isEqual:data()],"Invalid follower conversion must reject without a partial node or wire");};
  auto invalidFollower=[followerGesture mutableCopy];invalidFollower[@"kind"]=@"lfo";rejectFollower(invalidFollower);
  invalidFollower=[followerGesture mutableCopy];invalidFollower[@"audioInput"]=@{@"node":node};rejectFollower(invalidFollower);
  invalidFollower=[followerGesture mutableCopy];invalidFollower[@"audioInput"]=@{@"node":@"n9999999"};rejectFollower(invalidFollower);
  invalidFollower=[followerGesture mutableCopy];[invalidFollower removeObjectForKey:@"connect"];rejectFollower(invalidFollower);
  auto discreteBefore=data();
  auto discreteSource=call(@"graph.node.add",@{@"graph":graph,@"kind":@"lfo",@"connect":@{@"node":node,@"port":@3,@"output":@NO,@"modulation":@YES,@"base":@0,@"quantized":@YES}},true)[@"data"][@"node"];
  auto discreteState=data();auto discreteEdge=[discreteState[@"library"][0][@"modulation"] lastObject];
  check([discreteEdge[@"source"] isEqual:discreteSource]&&[discreteEdge[@"quantized"] boolValue],"Recipe source creation retains its explicit discrete target mode");
  call(@"history.undo",@{},true);check([discreteBefore isEqual:data()],"Discrete source and target mode share one Undo");
  call(@"history.redo",@{},true);check([discreteState isEqual:data()],"Redo restores recipe discrete mode");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[discreteState isEqual:data()],"Recipe discrete mode survives project reopen");
  call(@"graph.node.remove",@{@"graph":graph,@"node":discreteSource},true);
  auto returnBefore=data();auto send=call(@"mixer.bus.add",@{@"kind":@"return",@"sendFrom":target,@"position":@{@"x":@800,@"y":@120}},true)[@"data"][@"bus"];
  auto returnAfter=data();NSArray *sends=returnAfter[@"mixer"][@"buses"][0][@"sends"];
  check([[sends lastObject][@"target"] isEqual:send]&&![[sends lastObject][@"enabled"] boolValue]&&[[sends lastObject][@"gainDB"] doubleValue]==-96,"A new send starts off while its dry route remains intact");
  call(@"history.undo",@{},true);check([returnBefore isEqual:data()],"Return, send and layout creation share one Undo");
  auto groupingBefore=data();NSString *groupingRevision=session.automationRevision;
  call(@"graph.group.create",@{@"graph":graph,@"nodes":@[node,extra],@"name":@"Dynamics",@"dryRun":@YES},true);
  check([groupingRevision isEqual:session.automationRevision]&&[groupingBefore isEqual:data()],"Grouping preview changes neither identity allocation nor history");
  NSString *boundary=call(@"graph.group.create",@{@"graph":graph,@"nodes":@[node,extra],@"name":@"Dynamics"},true)[@"data"][@"group"];
  auto groupingAfter=data();
  for(NSString *key in @[@"nodes",@"audio",@"modulation"])check([groupingBefore[@"library"][0][key] isEqual:groupingAfter[@"library"][0][key]],"Grouping changed processor state or a real cable");
  call(@"history.undo",@{},true);check([groupingBefore isEqual:data()],"A single Undo removes only the processing boundary");
  call(@"history.redo",@{},true);check([groupingAfter isEqual:data()],"Group Redo restores identity and members");
  NSString *nested=call(@"graph.group.create",@{@"graph":graph,@"nodes":@[node],@"parent":boundary,@"name":@"Inside"},true)[@"data"][@"group"];
  auto nestedAfter=data();groupingRevision=session.automationRevision;
  check(![call(@"graph.group.update",@{@"graph":graph,@"group":nested,@"name":@"Inside"},true)[@"changed"] boolValue]&&[groupingRevision isEqual:session.automationRevision],"Identical group edits create no Undo entry");
  NSError *groupError=nil;
  check(![session automationMethod:@"graph.group.create" params:@{@"graph":graph,@"nodes":@[node,extra],@"parent":boundary,@"expectedRevision":session.automationRevision} error:&groupError]&&[nestedAfter isEqual:data()],"Mixed-depth grouping is rejected atomically");
  check(![session automationMethod:@"graph.group.update" params:@{@"graph":graph,@"group":nested,@"name":@"Stale",@"expectedRevision":@"stale"} error:&groupError]&&[nestedAfter isEqual:data()],"Group edits retain revision guards");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[nestedAfter isEqual:data()],"Nested groups persist alongside unchanged recipes and routes");
  call(@"graph.clone",@{@"graph":graph,@"name":@"Grouped copy"},true);
  auto groupedCopy=[data()[@"library"] lastObject];
  check([groupedCopy[@"groups"] count]==2&&![[groupedCopy[@"groups"] firstObject][@"id"] isEqual:boundary],"Cloning allocates independent group identities");
  check([groupedCopy[@"groups"][1][@"parent"] isEqual:groupedCopy[@"groups"][0][@"id"]],"Cloned nested parent references point into the copy");
  call(@"graph.group.remove",@{@"graph":graph,@"group":boundary},true);
  auto remaining=data()[@"library"][0][@"groups"];
  check([remaining count]==1&&[remaining[0][@"parent"] isEqual:@""],"Ungroup preserves child boundaries at the former parent's depth");
  call(@"history.undo",@{},true);check([data()[@"library"][0] isEqual:nestedAfter[@"library"][0]],"Ungroup Undo restores the exact nesting");
  NSString *exportGraph=call(@"graph.create",@{@"name":@"Export fixture"},true)[@"data"][@"graph"];
  NSString *exportNode=call(@"graph.node.add",@{@"graph":exportGraph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"},@"insertEdge":@0},true)[@"data"][@"node"];
  NSString *exportGroup=call(@"graph.group.create",@{@"graph":exportGraph,@"nodes":@[exportNode],@"name":@"Reusable gain"},true)[@"data"][@"group"];
  auto exportBefore=data();revision=session.automationRevision;
  call(@"graph.group.export",@{@"graph":exportGraph,@"group":exportGroup,@"dryRun":@YES},true);
  check([revision isEqual:session.automationRevision]&&[exportBefore isEqual:data()],"Export preview preserves allocation, source state and history");
  call(@"graph.group.export",@{@"graph":exportGraph,@"group":exportGroup},true);
  auto exportAfter=data();auto exported=[exportAfter[@"library"] lastObject];
  check([exported[@"name"] isEqual:@"Reusable gain"]&&[exported[@"nodes"] count]==3&&[exported[@"audio"] count]==2,"Library export creates an independent playable recipe");
  check([[exportAfter[@"library"] subarrayWithRange:NSMakeRange(0,[exportBefore[@"library"] count])] isEqual:exportBefore[@"library"]],"Export never converts or replaces original processors");
  for(NSDictionary *n in exported[@"nodes"])check(![n[@"id"] isEqual:exportNode],"Export must allocate independent processor identities");
  call(@"history.undo",@{},true);check([exportBefore isEqual:data()],"One Undo removes only the new library entry");
  call(@"history.redo",@{},true);check([exportAfter isEqual:data()],"Export Redo restores the exact independent recipe");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[exportAfter isEqual:data()],"Exported library recipes survive native save/reopen");
  call(@"plugin.add",@{@"descriptor":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1",@"name":@"Gain",@"type":@0,@"subtype":@0,@"manufacturer":@0}},true);
  NSString *rackKey=[@"plugin:" stringByAppendingString:[data()[@"plugins"] lastObject][@"id"]];
  auto songGroupBefore=data();revision=session.automationRevision;
  NSDictionary *groupRequest=@{@"nodes":@[rackKey],@"name":@"Rack gain",@"positions":@[@{@"node":rackKey,@"x":@300,@"y":@180}]};
  auto groupPreview=[groupRequest mutableCopy];groupPreview[@"dryRun"]=@YES;call(@"graph.song.group.create",groupPreview,true);
  check([revision isEqual:session.automationRevision]&&[songGroupBefore isEqual:data()],"Song grouping preview preserves the rack and document");
  NSString *songGroup=call(@"graph.song.group.create",groupRequest,true)[@"data"][@"group"];
  auto songGroupAfter=data();check([songGroupAfter[@"groups"] count]==1&&[songGroupAfter[@"plugins"] isEqual:songGroupBefore[@"plugins"]]&&[songGroupAfter[@"mixer"] isEqual:songGroupBefore[@"mixer"]],"Song group wraps existing rack identities without changing their routing");
  call(@"history.undo",@{},true);check([songGroupBefore isEqual:data()],"Song group and initial positions share one Undo");call(@"history.redo",@{},true);check([songGroupAfter isEqual:data()],"Song group Redo restores exact identities");
  revision=session.automationRevision;call(@"graph.song.group.update",@{@"group":songGroup,@"name":@"Rack gain"},true);check([revision isEqual:session.automationRevision],"Identical song group edit is a no-op");
  call(@"graph.layout.set",@{@"groups":@[@{@"group":songGroup,@"x":@400,@"y":@200}]},true);
  auto songGroupMoved=data();bool moved=false;for(NSDictionary *position in songGroupMoved[@"layout"])if([position[@"node"] isEqual:rackKey])moved=[position[@"x"] doubleValue]==400&&[position[@"y"] doubleValue]==200;check(moved,"Song boundary move retains relative processor positions");
  call(@"graph.song.group.export",@{@"group":songGroup},true);auto songGroupExported=data();check([[songGroupExported[@"library"] lastObject][@"nodes"] count]==3,"Song group exports a real independent recipe");
  check([songGroupExported[@"plugins"] isEqual:songGroupBefore[@"plugins"]]&&[songGroupExported[@"mixer"] isEqual:songGroupBefore[@"mixer"]],"Export retains original rack and routes");
  call(@"history.undo",@{},true);check([songGroupMoved isEqual:data()],"Export is one Undo");call(@"history.redo",@{},true);
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[songGroupExported isEqual:data()],"Song groups and their independent exports survive native save/reopen");
  call(@"graph.song.group.remove",@{@"group":songGroup},true);check([data()[@"groups"] count]==0&&[data()[@"plugins"] count]==[songGroupBefore[@"plugins"] count],"Ungroup removes only the song boundary");
  auto cutBefore=data();revision=session.automationRevision;
  NSArray *cuts=@[@{@"kind":@"output",@"source":target,@"target":master},@{@"kind":@"graph-input",@"source":side,@"target":target,@"input":@1},@{@"kind":@"graph-output",@"source":target,@"target":master,@"output":@1}];
  call(@"graph.connections.remove",@{@"connections":@[]},true);check([revision isEqual:session.automationRevision],"Empty song cable batch preserves history");
  call(@"graph.connections.remove",@{@"connections":cuts,@"dryRun":@YES},true);check([revision isEqual:session.automationRevision]&&[cutBefore isEqual:data()],"Song cable preview preserves routes and history");
  NSError *cutError=nil;
  check(![session automationMethod:@"graph.connections.remove" params:@{@"connections":cuts,@"expectedRevision":@"stale"} error:&cutError]&&[cutBefore isEqual:data()],"Stale song cable batch cannot alter routes");
  auto invalidCuts=[cuts mutableCopy];[invalidCuts addObject:@{@"kind":@"insert",@"plugin":@"fixed-chain"}];
  check(![session automationMethod:@"graph.connections.remove" params:@{@"connections":invalidCuts,@"expectedRevision":revision} error:&cutError]&&[revision isEqual:session.automationRevision]&&[cutBefore isEqual:data()],"An implicit wire rejects the entire song cable batch");
  invalidCuts=[cuts mutableCopy];[invalidCuts addObject:cuts[0]];
  check(![session automationMethod:@"graph.connections.remove" params:@{@"connections":invalidCuts,@"expectedRevision":revision} error:&cutError]&&[cutBefore isEqual:data()],"Duplicate song cable references reject atomically");
  call(@"graph.connections.remove",@{@"connections":cuts},true);auto cutAfter=data();
  check([cutAfter[@"inputs"] count]==0&&[cutAfter[@"outputs"] count]==0&&[cutAfter[@"mixer"][@"buses"][0][@"output"] isEqual:@""],"Song cable cut removes only the requested routes");
  call(@"history.undo",@{},true);check([cutBefore isEqual:data()],"One Undo restores every cable from one cut gesture");call(@"history.redo",@{},true);check([cutAfter isEqual:data()],"Redo restores the exact cable cut");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[cutAfter isEqual:data()],"Song cable cuts survive save and reopen");
  [[NSFileManager defaultManager] removeItemAtPath:path error:nil];
  // A channel/master scope references implicit routing without enabling it.
  {
    TrackerSession *scoped=[TrackerSession new];NSError *problem=nil;
    auto api=[&](NSString *method,NSDictionary *params,bool write=false)->NSDictionary *{auto p=[params mutableCopy];if(write)p[@"expectedRevision"]=scoped.automationRevision;auto r=[scoped automationMethod:method params:p error:&problem];if(!r)throw std::runtime_error(std::string(method.UTF8String)+": "+problem.localizedDescription.UTF8String);return r[@"data"];};
    auto snapshot=[&](){return api(@"graph.get",@{@"includeImplicitMixer":@YES});};
    auto initial=snapshot();NSString *track=initial[@"mixer"][@"buses"][0][@"id"],*master=[initial[@"mixer"][@"buses"] lastObject][@"id"];
    api(@"graph.song.source.add",@{@"source":@{@"kind":@"follower",@"audioBus":master}},true);
    api(@"graph.song.source.add",@{@"source":@{@"kind":@"note-envelope",@"noteTarget":track}},true);
    auto linked=snapshot();check([linked[@"implicitMixer"] boolValue]&&[linked[@"mixer"] isEqual:initial[@"mixer"]],"Referencing implicit source scopes must preserve saved mixer routing");
    api(@"history.undo",@{},true);api(@"history.undo",@{},true);check([initial isEqual:snapshot()],"Source scope Undo restores implicit routing");
    api(@"history.redo",@{},true);api(@"history.redo",@{},true);check([linked isEqual:snapshot()],"Source scope Redo restores stable references");
    api(@"pattern.create",@{@"rows":@32},true);check([snapshot()[@"songSources"] isEqual:linked[@"songSources"]],"Unrelated pattern edits must not reconcile away implicit source scopes");
    auto stored=snapshot();NSString *saved=[NSTemporaryDirectory() stringByAppendingPathComponent:[NSUUID.UUID.UUIDString stringByAppendingString:@".screamseq"]];
    check([scoped savePath:saved error:&problem]&&[scoped openPath:saved error:&problem]&&[stored isEqual:snapshot()],"Implicit source scopes must survive native save and reopen");
    auto revision=scoped.automationRevision;
    check(![scoped automationMethod:@"graph.song.source.add" params:@{@"source":@{@"kind":@"note-envelope",@"noteTarget":@"n999999"},@"expectedRevision":revision} error:&problem]&&[revision isEqual:scoped.automationRevision]&&[stored isEqual:snapshot()],"Invalid implicit source scopes reject without mutation");
    [[NSFileManager defaultManager] removeItemAtPath:saved error:nil];
  }
  // Blank-canvas Add retains a real unconnected processor and one Undo entry.
  {
    TrackerSession *loose=[TrackerSession new];NSError *problem=nil;
    auto api=[&](NSString *method,NSDictionary *params,bool write=false)->NSDictionary *{auto p=[params mutableCopy];if(write)p[@"expectedRevision"]=loose.automationRevision;auto r=[loose automationMethod:method params:p error:&problem];if(!r)throw std::runtime_error(std::string(method.UTF8String)+": "+problem.localizedDescription.UTF8String);return r[@"data"];};
    auto snapshot=[&](){return api(@"graph.get",@{@"includeImplicitMixer":@YES});};
    auto initial=snapshot();NSDictionary *descriptor=@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1",@"name":@"Gainer",@"type":@0,@"subtype":@0,@"manufacturer":@0};
    auto add=@{@"descriptor":descriptor,@"detached":@YES,@"position":@{@"x":@900,@"y":@150}};
    api(@"plugin.add",add,true);auto added=snapshot();NSString *plugin=added[@"plugins"][0][@"id"];
    check([added[@"mixer"][@"detached"] isEqual:@[plugin]]&&[added[@"implicitMixer"] boolValue]&&[added[@"layout"] count]==1,"Detached Add must not create a Master insert or explicit saved buses");
    auto looseRevision=loose.automationRevision;
    api(@"mixer.inserts.detach",@{@"plugins":@[plugin]},true);
    check([looseRevision isEqual:loose.automationRevision]&&[added isEqual:snapshot()],"Repeated detach must not materialize implicit mixer buses or change history");
    api(@"mixer.inserts.detach",@{@"plugins":@[plugin],@"positions":@[@{@"node":[@"plugin:" stringByAppendingString:plugin],@"x":@900,@"y":@150}]},true);
    check([looseRevision isEqual:loose.automationRevision]&&[added isEqual:snapshot()],"Repeated detach with existing placement is also an implicit-mixer no-op");
    api(@"history.undo",@{},true);check([initial isEqual:snapshot()],"One Undo removes loose plugin, routing marker and position");
    api(@"history.redo",@{},true);check([added isEqual:snapshot()],"Redo restores exact loose processor identity and location");
    api(@"mixer.enable",@{},true);api(@"mixer.enable",@{@"enabled":@NO},true);
    check([added isEqual:snapshot()],"Returning to implicit routing never assigns an unconnected effect to Master");
    NSString *target=added[@"mixer"][@"buses"][0][@"id"];
    api(@"mixer.inserts.move",@{@"plugins":@[plugin],@"target":target},true);
    auto moved=snapshot();check([moved[@"mixer"][@"detached"] count]==0&&[moved[@"mixer"][@"buses"][0][@"inserts"] isEqual:@[plugin]],"Moving a loose processor into a channel establishes exactly one insert owner");
    NSDictionary *detach=@{@"plugins":@[plugin],@"positions":@[@{@"node":[@"plugin:" stringByAppendingString:plugin],@"x":@1100,@"y":@330}]};
    auto preview=[detach mutableCopy];preview[@"dryRun"]=@YES;api(@"mixer.inserts.detach",preview,true);check([moved isEqual:snapshot()],"Detach dry-run preserves entire graph");
    api(@"mixer.inserts.detach",detach,true);auto pulled=snapshot();
    check([pulled[@"mixer"][@"detached"] isEqual:@[plugin]]&&[pulled[@"mixer"][@"buses"][0][@"inserts"] count]==0&&[pulled[@"plugins"] isEqual:moved[@"plugins"]],"Detach preserves processor while healing its main path");
    auto noOp=loose.automationRevision;api(@"mixer.inserts.detach",detach,true);check([noOp isEqual:loose.automationRevision],"Repeated detach has no history/revision change");
    api(@"history.undo",@{},true);check([moved isEqual:snapshot()],"One Undo restores attachment and old position");api(@"history.redo",@{},true);check([pulled isEqual:snapshot()],"Redo preserves detached identity/position");api(@"history.undo",@{},true);
    api(@"history.undo",@{},true);check([added isEqual:snapshot()],"Undo insertion returns the same processor to its unconnected state");
    NSString *saved=[NSTemporaryDirectory() stringByAppendingPathComponent:[NSUUID.UUID.UUIDString stringByAppendingString:@".screamseq"]];
    check([loose savePath:saved error:&problem]&&[loose openPath:saved error:&problem]&&[added isEqual:snapshot()],"Unconnected processor marker and placement must survive native save/reopen");
    api(@"plugin.remove",@{@"plugins":@[plugin]},true);check([snapshot()[@"mixer"][@"detached"] count]==0,"Removing a loose plugin clears its disconnected marker");
    api(@"history.undo",@{},true);check([added isEqual:snapshot()],"Undo loose removal preserves marker, stable identity and position");
    auto revision=loose.automationRevision;auto bad=[add mutableCopy];bad[@"target"]=target;bad[@"expectedRevision"]=revision;
    check(![loose automationMethod:@"plugin.add" params:bad error:&problem]&&[revision isEqual:loose.automationRevision]&&[added isEqual:snapshot()],"Conflicting loose/assigned Add rejects atomically");
    [[NSFileManager defaultManager] removeItemAtPath:saved error:nil];
  }
  // Song controls act on an existing rack instance and share document history.
  {
    TrackerSession *mod=[TrackerSession new];NSError *problem=nil;
    auto api=[&](NSString *method,NSDictionary *params,bool write=false)->NSDictionary *{auto p=[params mutableCopy];if(write)p[@"expectedRevision"]=mod.automationRevision;auto r=[mod automationMethod:method params:p error:&problem];if(!r)throw std::runtime_error(std::string(method.UTF8String)+": "+problem.localizedDescription.UTF8String);return r[@"data"];};
    auto snapshot=[&](){return api(@"graph.get",@{});};
    api(@"plugin.add",@{@"descriptor":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1",@"name":@"Gainer",@"type":@0,@"subtype":@0,@"manufacturer":@0}},true);
    NSString *plugin=snapshot()[@"plugins"][0][@"id"];
    NSString *sourceGroup=api(@"graph.song.group.create",@{@"nodes":@[[ @"plugin:" stringByAppendingString:plugin]],@"name":@"Dynamics"},true)[@"group"];
    NSDictionary *add=@{@"source":@{@"kind":@"lfo",@"name":@"Movement",@"rate":@2},@"connect":@{@"plugin":plugin,@"parameter":@1},@"parent":sourceGroup};
    auto before=snapshot();auto rev=mod.automationRevision;
    auto preview=[add mutableCopy];preview[@"dryRun"]=@YES;api(@"graph.song.source.add",preview,true);
    check([rev isEqual:mod.automationRevision]&&[before isEqual:snapshot()],"Song source dry-run changed identities/history");
    NSString *source=api(@"graph.song.source.add",add,true)[@"node"];auto connected=snapshot();
    check([connected[@"songSources"] count]==1&&[connected[@"songModulation"] count]==1&&[connected[@"songModulation"][0][@"maximum"] doubleValue]==0,"Add source connects at zero depth");
    check([connected[@"groups"][0][@"nodes"] containsObject:[@"source:" stringByAppendingString:source]],"A source added inside a song group must join that group atomically");
    check([before[@"plugins"] isEqual:connected[@"plugins"]]&&[before[@"mixer"] isEqual:connected[@"mixer"]],"Song modulation replaced rack instances or routing");
    api(@"history.undo",@{},true);check([before isEqual:snapshot()],"One Undo must remove source and zero-depth connection");
    api(@"history.redo",@{},true);check([connected isEqual:snapshot()],"Redo must restore source and stable target identities");
    NSDictionary *depth=@{@"source":source,@"plugin":plugin,@"parameter":@1,@"minimum":@(-.2),@"maximum":@.3};
    api(@"graph.song.modulation.set",depth,true);auto depthState=snapshot();rev=mod.automationRevision;
    api(@"graph.song.modulation.set",depth,true);check([rev isEqual:mod.automationRevision],"Identical song modulation depth created Undo");
    NSString *activityKey=nil;for(NSDictionary *candidate in api(@"parameter.activity.targets",@{})[@"targets"])if([candidate[@"plugin"] isEqual:plugin])activityKey=candidate[@"key"];
    check(activityKey!=nil,"Song modulation target missing from parameter activity");
    auto activitySources=api(@"parameter.activity.sources",@{@"target":activityKey,@"parameter":@1})[@"sources"];
    bool hasBase=false,hasSource=false;
    for(NSDictionary *candidate in activitySources)if([candidate[@"scope"] isEqual:@"song"]){
      check(candidate[@"graph"]==NSNull.null&&[candidate[@"plugin"] isEqual:plugin],"Song source activity must retain root scope and rack identity");
      hasBase|=[candidate[@"id"] isEqual:@"n0"]&&candidate[@"node"]==nil;
      hasSource|=[candidate[@"node"] isEqual:source]&&[candidate[@"id"] isEqual:source]&&[candidate[@"parameter"] unsignedIntValue]==1&&[candidate[@"minimum"] doubleValue]==-.2&&[candidate[@"maximum"] doubleValue]==.3;
    }
    check(hasBase&&hasSource&&[rev isEqual:mod.automationRevision],"Activity must expose the unmodulated base and stable source edit link without editing the song");
    auto rejectSong=[&](NSString *method,NSDictionary *p){auto guarded=[p mutableCopy];guarded[@"expectedRevision"]=mod.automationRevision;NSError *failure=nil;auto state=snapshot();auto revision=mod.automationRevision;
      check(![mod automationMethod:method params:guarded error:&failure],"Invalid song control edit accepted");check([state isEqual:snapshot()]&&[revision isEqual:mod.automationRevision],"Invalid song control partially committed");return failure.code;};
    for(id parent in @[@"n999999",@YES,NSNull.null])check(rejectSong(@"graph.song.source.add",@{@"source":@{@"kind":@"lfo"},@"parent":parent})==-32602,"Invalid source parent is a validation error, not an engine failure");
    auto staleAdd=[add mutableCopy];staleAdd[@"expectedRevision"]=@"stale";
    check(![mod automationMethod:@"graph.song.source.add" params:staleAdd error:&problem]&&[depthState isEqual:snapshot()],"A stale grouped-source add must not change allocator, membership or routes");
    rejectSong(@"graph.song.modulation.set",@{@"source":source,@"plugin":plugin,@"parameter":@1,@"minimum":@(-2)});
    rejectSong(@"graph.song.modulation.set",@{@"source":source,@"plugin":plugin,@"parameter":@YES});
    rejectSong(@"graph.song.modulation.set",@{@"source":source,@"plugin":plugin,@"parameter":@99999});
    rejectSong(@"graph.song.modulation.set",@{@"source":source,@"plugin":plugin,@"parameter":@1,@"quantized":@YES});
    rejectSong(@"graph.song.source.update",@{@"node":source,@"source":@{@"kind":@"random"}});
    rejectSong(@"graph.song.source.update",@{@"node":source,@"source":@{@"unexpected":@1}});
    rejectSong(@"graph.song.source.remove",@{@"nodes":@[source,source]});
    rejectSong(@"graph.song.source.remove",@{@"nodes":@[source,@"n999999"]});
    api(@"graph.song.source.update",@{@"node":source,@"source":@{@"rate":@3}},true);
    auto updated=snapshot();check([updated[@"songSources"][0][@"rate"] doubleValue]==3&&[updated[@"songSources"][0][@"name"] isEqual:@"Movement"]&&[updated[@"songModulation"] isEqual:depthState[@"songModulation"]],"Source patch overwrote unrelated settings or cables");
    NSString *curveSource=api(@"graph.song.source.add",@{@"source":@{@"kind":@"automation",@"name":@"Curve"}},true)[@"node"];
    auto beforeReroute=snapshot();NSDictionary *oldEndpoint=@{@"source":source,@"plugin":plugin,@"parameter":@1};
    api(@"graph.song.modulation.set",@{@"source":curveSource,@"plugin":plugin,@"parameter":@1,@"replace":oldEndpoint},true);
    auto rerouted=snapshot()[@"songModulation"];check([rerouted count]==1&&[rerouted[0][@"source"] isEqual:curveSource]&&[rerouted[0][@"minimum"] doubleValue]==-.2&&[rerouted[0][@"maximum"] doubleValue]==.3,"Endpoint reroute must retain the old depth and remove only its old identity");
    api(@"history.undo",@{},true);check([beforeReroute isEqual:snapshot()],"One Undo must restore both modulation endpoints and range");
    rev=mod.automationRevision;api(@"graph.song.modulation.set",@{@"source":source,@"plugin":plugin,@"parameter":@1,@"replace":oldEndpoint},true);check([rev isEqual:mod.automationRevision],"Identical endpoint reroute must not create history");
    api(@"graph.song.modulation.set",@{@"source":curveSource,@"plugin":plugin,@"parameter":@1},true);
    rejectSong(@"graph.song.modulation.set",@{@"source":curveSource,@"plugin":plugin,@"parameter":@1,@"replace":oldEndpoint});
    api(@"graph.song.modulation.remove",@{@"connections":@[@{@"source":curveSource,@"plugin":plugin,@"parameter":@1}]},true);
    NSDictionary *curveTarget=@{@"kind":@"graph",@"graph":NSNull.null,@"node":curveSource,@"pattern":@0};
    NSDictionary *curveParams=@{@"graph":NSNull.null,@"node":curveSource,@"pattern":@0,@"points":@[@{@"position":@0,@"value":@0},@{@"position":@256,@"value":@1}]};
    api(@"graph.automation.set",curveParams,true);
    check([api(@"graph.automation.get",@{@"graph":NSNull.null,@"node":curveSource,@"pattern":@0})[@"points"] count]==2,"Song curve was not available in envelope editor");
    NSString *templateID=api(@"envelope.bank.save",@{@"target":curveTarget,@"name":@"Song movement"},true)[@"id"];
    api(@"envelope.bank.apply",@{@"template":templateID,@"target":curveTarget,@"linked":@YES},true);
    check([api(@"envelope.bank.list",@{@"target":curveTarget})[@"linkedTemplate"] isEqual:templateID],"Song source template link unavailable");
    rejectSong(@"graph.automation.set",@{@"graph":NSNull.null,@"node":curveSource,@"pattern":@0,@"points":@[@{@"position":@0,@"value":@.8}]});
    NSDictionary *parameterTarget=@{@"kind":@"parameter",@"pattern":@0,@"plugin":plugin,@"parameter":@1};
    api(@"envelope.bank.apply",@{@"template":templateID,@"target":parameterTarget,@"linked":@YES},true);
    auto sharedBefore=snapshot();auto parameterBefore=api(@"envelope.bank.list",@{@"target":parameterTarget});
    auto shape=[api(@"envelope.bank.list",@{@"target":curveTarget})[@"shape"] mutableCopy];
    auto points=[shape[@"points"] mutableCopy];auto point=[points[0] mutableCopy];point[@"value"]=@.6;points[0]=point;shape[@"points"]=points;
    api(@"envelope.bank.save",@{@"id":templateID,@"name":@"Shared movement",@"shape":shape},true);
    auto sharedAfter=snapshot();auto parameterAfter=api(@"envelope.bank.list",@{@"target":parameterTarget});
    check([api(@"graph.automation.get",@{@"graph":NSNull.null,@"node":curveSource,@"pattern":@0})[@"points"][0][@"value"] doubleValue]==.6&&[parameterAfter[@"shape"][@"points"][0][@"value"] doubleValue]==.6,"One bank update must change both song source and ordinary parameter envelope");
    api(@"history.undo",@{},true);check([sharedBefore isEqual:snapshot()]&&[parameterBefore isEqual:api(@"envelope.bank.list",@{@"target":parameterTarget})],"One Undo restores both kinds of linked envelope and their common template");
    api(@"history.redo",@{},true);check([sharedAfter isEqual:snapshot()]&&[parameterAfter isEqual:api(@"envelope.bank.list",@{@"target":parameterTarget})],"One Redo restores the complete compound envelope update");
    auto stored=snapshot();NSString *saved=[NSTemporaryDirectory() stringByAppendingPathComponent:[NSUUID.UUID.UUIDString stringByAppendingString:@".screamseq"]];
    check([mod savePath:saved error:&problem]&&[mod openPath:saved error:&problem]&&[stored isEqual:snapshot()],"Song sources, edges and bank link failed roundtrip");
    NSArray *edgeRefs=@[@{@"source":source,@"plugin":plugin,@"parameter":@1}];
    auto stableRev=mod.automationRevision;api(@"graph.song.modulation.remove",@{@"connections":@[]},true);check([stableRev isEqual:mod.automationRevision],"Empty modulation deletion made history");
    api(@"graph.song.modulation.remove",@{@"connections":edgeRefs},true);check([snapshot()[@"songModulation"] count]==0,"Song modulation edge removal failed");
    api(@"history.undo",@{},true);check([stored isEqual:snapshot()],"Song edge Undo failed");
    api(@"graph.song.source.remove",@{@"nodes":@[source,curveSource]},true);check([snapshot()[@"songSources"] count]==0&&[snapshot()[@"songModulation"] count]==0,"Source deletion left dangling sources/edges");
    api(@"history.undo",@{},true);check([stored isEqual:snapshot()]&&[api(@"envelope.bank.list",@{@"target":curveTarget})[@"linkedTemplate"] isEqual:templateID],"Source deletion Undo lost linked envelope or routing");
    [[NSFileManager defaultManager] removeItemAtPath:saved error:nil];
  }
  {
    TrackerSession *visual=[TrackerSession new];NSError *problem=nil;
    auto api=[&](NSString *method,NSDictionary *params,bool write=false)->NSDictionary *{auto p=[params mutableCopy];if(write)p[@"expectedRevision"]=visual.automationRevision;auto r=[visual automationMethod:method params:p error:&problem];if(!r)throw std::runtime_error(std::string(method.UTF8String)+": "+problem.localizedDescription.UTF8String);return r[@"data"];};
    auto snapshot=[&](){return api(@"graph.get",@{@"includeImplicitMixer":@YES});};auto initial=snapshot();NSString *track=initial[@"mixer"][@"buses"][0][@"id"],*master=[initial[@"mixer"][@"buses"] lastObject][@"id"];
    NSDictionary *presentation=@{@"collapsedNodes":@[track],@"regions":@[@{@"id":@"frame-a",@"kind":@"frame",@"title":@"Rhythm",@"x":@10,@"y":@20,@"nodes":@[track]}],@"cables":@[@{@"source":track,@"target":master,@"points":@[@[@220,@160]]}]};
    NSString *revision=visual.automationRevision;api(@"graph.presentation.set",@{@"presentation":presentation,@"dryRun":@YES},true);check([revision isEqual:visual.automationRevision]&&[initial isEqual:snapshot()],"Presentation preview mutated song");
    api(@"graph.presentation.set",@{@"presentation":presentation,@"positions":@[@{@"node":track,@"x":@50,@"y":@80}]},true);auto saved=snapshot();check([saved[@"implicitMixer"] boolValue]&&[saved[@"presentation"][@"regions"] count]==1&&[saved[@"presentation"][@"collapsedNodes"] isEqual:@[track]],"Visual frame materialized routing or disappeared");
    revision=visual.automationRevision;api(@"graph.presentation.set",@{@"presentation":saved[@"presentation"]},true);check([revision isEqual:visual.automationRevision],"Identical presentation write created history");
    check(![visual automationMethod:@"graph.presentation.set" params:@{@"expectedRevision":@"stale",@"presentation":@{}} error:&problem]&&[saved isEqual:snapshot()],"Stale presentation write changed geometry");
    for(id bad in @[@[track,track],@[@YES],@[@""]])check(![visual automationMethod:@"graph.presentation.set" params:@{@"expectedRevision":visual.automationRevision,@"presentation":@{@"collapsedNodes":bad}} error:&problem]&&[saved isEqual:snapshot()],"Invalid compact node keys changed presentation");
    api(@"history.undo",@{},true);check([initial isEqual:snapshot()],"Frame plus member movement must be one Undo");api(@"history.redo",@{},true);check([saved isEqual:snapshot()],"Presentation Redo changed routing");
    NSString *path=[NSTemporaryDirectory() stringByAppendingPathComponent:[NSUUID.UUID.UUIDString stringByAppendingString:@".screamseq"]];check([visual savePath:path error:&problem]&&[visual openPath:path error:&problem]&&[saved isEqual:snapshot()],"Graph annotations/reroute points failed project roundtrip");[[NSFileManager defaultManager] removeItemAtPath:path error:nil];
  }
  {
    TrackerSession *provenance=[TrackerSession new];NSError *problem=nil;
    auto api=[&](NSString *method,NSDictionary *params,bool write=false)->NSDictionary *{auto p=[params mutableCopy];if(write)p[@"expectedRevision"]=provenance.automationRevision;auto r=[provenance automationMethod:method params:p error:&problem];if(!r)throw std::runtime_error(std::string(method.UTF8String)+": "+problem.localizedDescription.UTF8String);return r[@"data"];};
    auto revision=provenance.automationRevision;
    auto empty=api(@"graph.provenance.get",@{@"plugin":@"unloaded-plugin",@"parameter":@(UINT32_MAX)});
    check([empty[@"sources"] count]==0&&[empty[@"total"] intValue]==0&&[revision isEqual:provenance.automationRevision],"Stopped unloaded provenance query changed song or required a live processor");
    for(NSDictionary *bad in @[@{@"plugin":@"x",@"parameter":@YES},@{@"plugin":@"x",@"parameter":@1,@"limit":@257},@{@"plugin":@"x",@"parameter":@1,@"extra":@1}])check(![provenance automationMethod:@"graph.provenance.get" params:bad error:&problem]&&[revision isEqual:provenance.automationRevision],"Malformed provenance query was accepted or edited song");
    auto result=api(@"plugin.add",@{@"descriptor":@{@"format":@"Built-in",@"name":@"Gain",@"classID":@"resonance.gainer.v1",@"type":@0,@"subtype":@0,@"manufacturer":@0}},true);
    auto plugin=result[@"plugin"];if(![plugin isKindOfClass:NSString.class])plugin=api(@"graph.get",@{})[@"plugins"][0][@"id"];
    api(@"automation.pattern.set",@{@"plugin":plugin,@"parameter":@1,@"pattern":@0,@"enabled":@NO,@"points":@[@{@"position":@4096,@"value":@.2},@{@"position":@8192,@"value":@.8}]},true);
    revision=provenance.automationRevision;auto page=api(@"graph.provenance.get",@{@"plugin":plugin,@"parameter":@1,@"pattern":@0,@"limit":@1});
    check([page[@"total"] intValue]==1&&[page[@"sources"][0][@"kind"] isEqual:@"envelope"]&&![page[@"sources"][0][@"enabled"] boolValue]&&[page[@"sources"][0][@"position"] intValue]==16*65536&&[revision isEqual:provenance.automationRevision],"Provenance lost disabled envelope identity or precise row units");
    check([api(@"graph.provenance.get",@{@"plugin":plugin,@"parameter":@1,@"offset":@1})[@"sources"] count]==0,"Provenance pagination ignored offset");
  }
  {
    TrackerSession *bypass=[TrackerSession new];NSError *problem=nil;
    auto api=[&](NSString *method,NSDictionary *params,bool write=false)->NSDictionary *{auto p=[params mutableCopy];if(write)p[@"expectedRevision"]=bypass.automationRevision;auto r=[bypass automationMethod:method params:p error:&problem];if(!r)throw std::runtime_error(std::string(method.UTF8String)+": "+problem.localizedDescription.UTF8String);return r;};
    auto snapshot=[&](){return api(@"graph.get",@{})[@"data"];};
    NSString *graph=api(@"graph.create",@{@"name":@"Bypass recipe"},true)[@"data"][@"graph"];
    NSString *node=api(@"graph.node.add",@{@"graph":graph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"},@"insertEdge":@0},true)[@"data"][@"node"];
    api(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-6)}]},true);
    auto baseline=api(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"];
    check(![baseline[@"bypass"] boolValue],"New recipe processor must be enabled by default");
    auto before=snapshot();NSString *revision=bypass.automationRevision;
    check(![api(@"graph.plugin.bypass",@{@"graph":graph,@"node":node,@"bypass":@YES,@"dryRun":@YES},true)[@"changed"] boolValue]&&[revision isEqual:bypass.automationRevision]&&[before isEqual:snapshot()],"Bypass dry-run mutates recipe/history");
    for(NSDictionary *bad in @[@{@"graph":graph,@"node":node,@"bypass":@1},@{@"graph":graph,@"node":node},@{@"graph":graph,@"node":node,@"bypass":@YES,@"parameters":@[]},@{@"graph":graph,@"node":@"n999999",@"bypass":@YES}]){
      auto p=[bad mutableCopy];p[@"expectedRevision"]=revision;check(![bypass automationMethod:@"graph.plugin.bypass" params:p error:&problem]&&[before isEqual:snapshot()]&&[revision isEqual:bypass.automationRevision],"Invalid recipe bypass partially committed");
    }
    check([api(@"graph.plugin.bypass",@{@"graph":graph,@"node":node,@"bypass":@YES},true)[@"data"][@"bypass"] boolValue],"Bypass API did not return persisted requested state");
    auto after=snapshot();auto metadata=api(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"];
    check([metadata[@"bypass"] boolValue]&&[metadata[@"parameters"] isEqual:baseline[@"parameters"]],"Host bypass must not rewrite vendor/manual parameters");
    check(![bypass automationMethod:@"graph.plugin.bypass" params:@{@"graph":graph,@"node":node,@"bypass":@NO,@"expectedRevision":revision} error:&problem]&&[after isEqual:snapshot()],"Stale bypass must preserve exact graph");
    revision=bypass.automationRevision;api(@"graph.plugin.bypass",@{@"graph":graph,@"node":node,@"bypass":@YES},true);check([revision isEqual:bypass.automationRevision],"Identical bypass adds history");
    api(@"history.undo",@{},true);check([before isEqual:snapshot()],"One Undo restores recipe bypass and baseline");api(@"history.redo",@{},true);check([after isEqual:snapshot()],"Redo restores exact bypass state");
    auto clone=api(@"graph.clone",@{@"graph":graph},true)[@"data"][@"graph"];bool copied=false;
    for(NSDictionary *definition in snapshot()[@"library"])if([definition[@"id"] isEqual:clone])for(NSDictionary *item in definition[@"nodes"])if([item[@"kind"] isEqual:@"plugin"])copied=[item[@"plugin"][@"bypass"] boolValue];
    check(copied,"Cloning a recipe lost per-node bypass");
    NSString *group=api(@"graph.group.create",@{@"graph":graph,@"nodes":@[node]},true)[@"data"][@"group"];
    auto exported=api(@"graph.group.export",@{@"graph":graph,@"group":group},true)[@"data"][@"graph"];copied=false;
    for(NSDictionary *definition in snapshot()[@"library"])if([definition[@"id"] isEqual:exported])for(NSDictionary *item in definition[@"nodes"])if([item[@"kind"] isEqual:@"plugin"])copied=[item[@"plugin"][@"bypass"] boolValue];
    check(copied,"Exporting a processing group lost per-node bypass");
    auto saved=snapshot();NSString *path=[NSTemporaryDirectory() stringByAppendingPathComponent:[NSUUID.UUID.UUIDString stringByAppendingString:@".screamseq"]];
    check([bypass savePath:path error:&problem]&&[bypass openPath:path error:&problem]&&[saved isEqual:snapshot()],"Recipe bypass lost on save/reopen");[[NSFileManager defaultManager] removeItemAtPath:path error:nil];
  }
  graphEditingSessionChecks();
  graphStageSessionChecks();
  std::cout<<"PASS graph API: preview, identity allocation, guarded atomic edits, assignment and group-capable lanes, Undo/Redo, recipe/state project roundtrip, independent clone identities\n";return 0;
}catch(const std::exception &e){std::cerr<<e.what()<<'\n';return 1;}}}
