#import "../Bridge/TrackerSession.h"
#include "../Audio/AudioUnitHost.hpp"
#include "editor/TrackerDocument.hpp"
#include <iostream>
using namespace Tracker;
static void check(bool b,const char *message){if(!b)throw std::runtime_error(message);}
int main(){@autoreleasepool{try{
  TrackerSession *session=[TrackerSession new];NSError *error=nil;
  auto call=[&](NSString *method,NSDictionary *parameters,bool write=false)->NSDictionary *{auto p=[parameters mutableCopy];if(write)p[@"expectedRevision"]=session.automationRevision;auto response=[session automationMethod:method params:p error:&error];if(!response)throw std::runtime_error(error.localizedDescription.UTF8String);return response;};
  auto data=[&](){return call(@"graph.get",@{})[@"data"];};
  auto empty=data();NSString *revision=session.automationRevision;
  auto signals=call(@"graph.signal.get",@{});
  check(![signals[@"changed"] boolValue] && ![signals[@"data"][@"active"] boolValue] && [revision isEqual:session.automationRevision],"Signal observation is a read and explicitly distinguishes stopped transport");
  NSError *signalError=nil;
  check(![session automationMethod:@"graph.signal.clear" params:@{@"port":@"missing/out/0",@"expectedRevision":revision} error:&signalError] && [revision isEqual:session.automationRevision],"An unknown observation target cannot alter the song");
  auto scope=call(@"graph.scope.get",@{@"spectrum":@YES});check(scope[@"data"][@"port"]==NSNull.null && [scope[@"data"][@"frames"] integerValue]==0,"No prepared scope is explicitly empty");
  check(call(@"graph.listen.get",@{})[@"data"][@"port"]==NSNull.null,"A new session has no monitor override");
  check(![call(@"graph.listen.set",@{@"port":NSNull.null},true)[@"changed"] boolValue],"Stop listening is session state without Undo");
  check(![session automationMethod:@"graph.listen.set" params:@{@"port":@"missing/out/0",@"expectedRevision":revision} error:&signalError] && [revision isEqual:session.automationRevision],"Unknown monitor port is rejected unchanged");
  check(![call(@"graph.scope.watch",@{@"port":NSNull.null},true)[@"changed"] boolValue],"Stopping scope capture creates no song edit or Undo");
  check(![session automationMethod:@"graph.scope.watch" params:@{@"port":@"missing/out/0",@"expectedRevision":revision} error:&signalError] && [revision isEqual:session.automationRevision],"Unknown scope port is rejected unchanged");
  call(@"graph.create",@{@"name":@"Echo",@"dryRun":@YES},true);check([revision isEqual:session.automationRevision]&&[empty isEqual:data()],"Graph preview mutates document");
  NSString *graph=call(@"graph.create",@{@"name":@"Echo"},true)[@"data"][@"graph"];
  NSString *node=call(@"graph.node.add",@{@"graph":graph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"}},true)[@"data"][@"node"];
  NSMutableDictionary *definition=[data()[@"library"][0] mutableCopy];NSArray *nodes=definition[@"nodes"];
  definition[@"audio"]=@[@{@"source":nodes[0][@"id"],@"target":node},@{@"source":node,@"target":nodes[1][@"id"]}];
  call(@"graph.update",@{@"definition":definition},true);
  auto metadata=call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"];
  check([metadata[@"parameters"] count]>=2&&[metadata[@"buses"] count]>=2,"Graph recipe exposes parameters and ports");
  revision=session.automationRevision;
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-6)}],@"dryRun":@YES},true);
  check([revision isEqual:session.automationRevision],"Plugin recipe preview committed");
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-6)}]},true);
  auto parameters=call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"][@"parameters"];
  check([parameters[1][@"value"] doubleValue]==-6,"Graph plugin parameter did not persist in recipe");
  const auto parameterState=data();revision=session.automationRevision;
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-6)}]},true);
  check([revision isEqual:session.automationRevision],"Identical graph parameter write must preserve history");
  call(@"history.undo",@{},true);check([call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"][@"parameters"][1][@"value"] doubleValue]==0,"Undo removes an explicit baseline and restores preset value");
  call(@"history.redo",@{},true);check([parameterState isEqual:data()],"Redo restores exact explicit graph baseline");
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-9)}],@"gesture":@"drag-one"},true);
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-12)}],@"gesture":@"drag-one"},true);
  call(@"history.undo",@{},true);check([parameterState isEqual:data()],"One Undo restores the start of a graph parameter drag");
  call(@"history.redo",@{},true);auto dragState=data();
  call(@"graph.layout.set",@{@"positions":@[@{@"node":@"gesture-break",@"x":@1,@"y":@2}]},true);auto interleavedState=data();
  call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(-15)}],@"gesture":@"drag-one"},true);
  call(@"history.undo",@{},true);check([interleavedState isEqual:data()],"Intervening layout edits break graph drag coalescing");
  call(@"history.undo",@{},true);check([dragState isEqual:data()],"Interleaved layout retains its own Undo");
  call(@"history.undo",@{},true);check([parameterState isEqual:data()],"Earlier drag remains one Undo after an interleaved edit");
  call(@"graph.layout.set",@{@"positions":@[@{@"node":@"test-node",@"x":@125,@"y":@250}]},true);
  check([data()[@"layout"] count]==1,"Graph layout missing from API");
  call(@"mixer.enable",@{},true);NSString *target=data()[@"mixer"][@"buses"][0][@"id"];
  call(@"graph.assign",@{@"target":target,@"graph":graph,@"amount":@.4,@"wet":@.7},true);
  definition=[data()[@"library"][0] mutableCopy];NSMutableArray *audio=[definition[@"audio"] mutableCopy];[audio addObject:@{@"source":nodes[0][@"id"],@"target":nodes[1][@"id"],@"output":@1,@"input":@1}];definition[@"audio"]=audio;call(@"graph.update",@{@"definition":definition},true);
  NSString *side=data()[@"mixer"][@"buses"][1][@"id"],*master=[data()[@"mixer"][@"buses"] lastObject][@"id"];
  call(@"graph.routes.set",@{@"inputs":@[@{@"source":side,@"target":target,@"input":@1}],@"outputs":@[@{@"source":target,@"target":master,@"output":@1}]},true);
  call(@"graph.commands.set",@{@"pattern":@0,@"lanes":@[@{@"target":target,@"count":@2}],@"commands":@[@{@"target":target,@"graph":graph,@"kind":@"start",@"position":@32768,@"amount":@.2},@{@"target":target,@"kind":@"clear",@"position":@65536}]},true);
  NSString *automation=call(@"graph.node.add",@{@"graph":graph,@"kind":@"automation",@"name":@"Drawn motion"},true)[@"data"][@"node"];
  auto curveData=[&](){return call(@"graph.automation.get",@{@"graph":graph,@"node":automation,@"pattern":@0})[@"data"];};
  check([curveData()[@"points"] count]==0,"New graph curve must be empty");revision=session.automationRevision;
  NSDictionary *curve=@{@"graph":graph,@"node":automation,@"pattern":@0,@"points":@[@{@"position":@0,@"value":@0,@"curve":@"scripted",@"formula":@"mix(start,end,t^2)"},@{@"position":@255,@"value":@1,@"curve":@"step"}]};
  NSMutableDictionary *preview=[curve mutableCopy];preview[@"dryRun"]=@YES;call(@"graph.automation.set",preview,true);check([revision isEqual:session.automationRevision],"Graph curve preview mutates song");
  call(@"graph.automation.set",curve,true);check([curveData()[@"points"] count]==2,"Graph curve write missing");revision=session.automationRevision;call(@"graph.automation.set",curve,true);check([revision isEqual:session.automationRevision],"Identical graph curve creates Undo history");
  call(@"history.undo",@{@"domain":@"document"},true);check([curveData()[@"points"] count]==0,"Graph curve undo failed");call(@"history.redo",@{@"domain":@"document"},true);
  const auto instrument=[session addInstrument:1 error:&error];check(instrument>0,"Create instrument graph target");
  call(@"graph.instrument.assign",@{@"instrument":@(instrument),@"graph":graph,@"amount":@.3,@"wet":@.6},true);
  check([data()[@"instrumentAssignments"] count]==1,"Instrument graph assignment is missing");
  call(@"history.undo",@{@"domain":@"document"},true);check([data()[@"instrumentAssignments"] count]==0,"Instrument assignment undo failed");call(@"history.redo",@{@"domain":@"document"},true);
  auto modulatedDefinition=[data()[@"library"][0] mutableCopy];
  auto graphParameters=call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"][@"parameters"];
  NSDictionary *gainParameter=nil;for(NSDictionary *parameter in graphParameters)if([parameter[@"id"] integerValue]==1)gainParameter=parameter;
  modulatedDefinition[@"modulation"]=@[@{@"source":automation,@"target":node,@"parameter":@1,@"base":@.25,@"minimum":@0,@"maximum":@0}];
  call(@"graph.update",@{@"definition":modulatedDefinition},true);
  const double base=[gainParameter[@"min"] doubleValue]+.25*([gainParameter[@"max"] doubleValue]-[gainParameter[@"min"] doubleValue]);
  graphParameters=call(@"graph.plugin.get",@{@"graph":graph,@"node":node})[@"data"][@"parameters"];
  for(NSDictionary *parameter in graphParameters)if([parameter[@"id"] integerValue]==1)check(std::abs([parameter[@"value"] doubleValue]-base)<1e-5,"Graph inspector reports the modulation baseline in native units");
  revision=session.automationRevision;call(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@(base)}]},true);
  check([revision isEqual:session.automationRevision],"Setting the existing modulation baseline creates no spurious Undo");
  call(@"history.undo",@{},true);
  auto expected=data();revision=session.automationRevision;
  auto reject=[&](NSString *method,NSDictionary *parameters){auto p=[parameters mutableCopy];p[@"expectedRevision"]=session.automationRevision;NSError *failure=nil;check(![session automationMethod:method params:p error:&failure],"Invalid graph edit accepted");check([revision isEqual:session.automationRevision]&&[expected isEqual:data()],"Rejected graph edit partially committed");};
  reject(@"graph.automation.set",@{@"graph":graph,@"node":automation,@"pattern":@0,@"points":@[@{@"position":@0,@"value":@0},@{@"position":@0,@"value":@1}]});
  reject(@"graph.automation.set",@{@"graph":graph,@"node":node,@"pattern":@0,@"points":@[]});
  reject(@"graph.routes.set",@{@"inputs":@[@{@"source":master,@"target":target,@"input":@1}]});
  reject(@"graph.plugin.set",@{@"graph":graph,@"node":node,@"parameters":@[@{@"id":@1,@"value":@999}]});
  reject(@"graph.layout.set",@{@"positions":@[@{@"node":@"bad",@"x":@(-1),@"y":@0}]});
  reject(@"graph.remove",@{@"graph":graph});
  reject(@"graph.commands.set",@{@"pattern":@0,@"lanes":@[@{@"target":target,@"count":@0}]});
  definition=[expected[@"library"][0] mutableCopy];definition[@"audio"]=@[@{@"source":node,@"target":node}];reject(@"graph.update",@{@"definition":definition});
  call(@"history.undo",@{@"domain":@"document"},true);check([data()[@"instrumentAssignments"] count]==0,"Undo failed to remove instrument graph transaction");call(@"history.redo",@{@"domain":@"document"},true);check([expected isEqual:data()],"Redo lost graph identities or values");
  NSString *path=[NSTemporaryDirectory() stringByAppendingPathComponent:[NSUUID.UUID.UUIDString stringByAppendingString:@".screamseq"]];
  check([session savePath:path error:&error]&&[session openPath:path error:&error],"Graph project save/reload failed");check([expected isEqual:data()],"Graph project roundtrip lost data");
  call(@"graph.clone",@{@"graph":graph,@"name":@"Echo copy"},true);auto copied=data()[@"library"][1];check(![copied[@"id"] isEqual:graph]&&![copied[@"nodes"][0][@"id"] isEqual:expected[@"library"][0][@"nodes"][0][@"id"]],"Cloned graph reused identities");
  NSString *extra=call(@"graph.node.add",@{@"graph":graph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"}},true)[@"data"][@"node"];
  auto patchBefore=data();revision=session.automationRevision;
  NSDictionary *patch=@{@"graph":graph,@"nodes":@[extra],@"edge":@0,@"positions":@[@{@"node":extra,@"x":@325,@"y":@200}]};
  auto patchPreview=[patch mutableCopy];patchPreview[@"dryRun"]=@YES;call(@"graph.nodes.insert",patchPreview,true);
  check([revision isEqual:session.automationRevision]&&[patchBefore isEqual:data()],"Insertion dry-run must leave topology, layout and history unchanged");
  call(@"graph.nodes.insert",patch,true);auto patchAfter=data();
  check([patchAfter[@"library"][0][@"audio"] count]==[patchBefore[@"library"][0][@"audio"] count]+1,"Disconnected processor inserts on the selected wire");
  call(@"history.undo",@{@"domain":@"document"},true);check([patchBefore isEqual:data()],"One insertion Undo restores topology and position");
  call(@"history.redo",@{@"domain":@"document"},true);check([patchAfter isEqual:data()],"Insertion Redo restores exact wiring and layout");
  auto badPatch=[patch mutableCopy];badPatch[@"expectedRevision"]=session.automationRevision;badPatch[@"edge"]=@255;NSError *patchError=nil;
  check(![session automationMethod:@"graph.nodes.insert" params:badPatch error:&patchError]&&[patchAfter isEqual:data()],"An invalid insertion edge cannot move nodes or damage wiring");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[patchAfter isEqual:data()],"Inserted topology and layout persist with recipe state intact");
  auto detachPreview=call(@"graph.nodes.detach",@{@"graph":graph,@"nodes":@[extra],@"dryRun":@YES},true);
  check([detachPreview[@"data"][@"wouldChange"] boolValue]&&[patchAfter isEqual:data()],"Detach preview leaves processors and routes intact");
  call(@"graph.nodes.detach",@{@"graph":graph,@"nodes":@[extra],@"positions":@[@{@"node":extra,@"x":@600,@"y":@300}]},true);auto detached=data();
  check([detached[@"library"][0][@"audio"] count]+1==[patchAfter[@"library"][0][@"audio"] count],"Detach removes two boundary cables and adds exactly one bridge");
  call(@"history.undo",@{},true);check([patchAfter isEqual:data()],"Detach and move share one Undo");
  call(@"history.redo",@{},true);check([detached isEqual:data()],"Detach Redo retains layout and identities");
  call(@"history.undo",@{},true);
  call(@"graph.nodes.detach",@{@"graph":graph,@"nodes":@[extra],@"remove":@YES},true);
  check([data()[@"library"][0][@"nodes"] count]+1==[patchAfter[@"library"][0][@"nodes"] count],"Delete-and-heal removes only the selected effect");
  call(@"history.undo",@{},true);check([patchAfter isEqual:data()],"Delete-and-heal restores exact state in one Undo");
  auto addBefore=data();auto addRevision=session.automationRevision;
  NSDictionary *insertNew=@{@"graph":graph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"},@"insertEdge":@0,@"x":@510,@"y":@220};
  auto newPreview=[insertNew mutableCopy];newPreview[@"dryRun"]=@YES;call(@"graph.node.add",newPreview,true);
  check([addRevision isEqual:session.automationRevision]&&[addBefore isEqual:data()],"Add at edge dry-run changes no state or identity allocator");
  NSString *inserted=call(@"graph.node.add",insertNew,true)[@"data"][@"node"];
  auto addAfter=data(),oldEdge=addBefore[@"library"][0][@"audio"][0],newEdge=addAfter[@"library"][0][@"audio"][0];
  check([newEdge[@"source"] isEqual:inserted]&&[newEdge[@"target"] isEqual:oldEdge[@"target"]]&&[addAfter[@"library"][0][@"audio"] count]==[addBefore[@"library"][0][@"audio"] count]+1,"New processor splits precisely the selected cable");
  call(@"history.undo",@{},true);check([addBefore isEqual:data()],"One Undo restores cable and removes added node");
  call(@"history.redo",@{},true);check([addAfter isEqual:data()],"Add-and-connect Redo preserves identities");
  auto invalidAdd=[insertNew mutableCopy];invalidAdd[@"insertEdge"]=@255;invalidAdd[@"expectedRevision"]=session.automationRevision;NSError *addError=nil;
  check(![session automationMethod:@"graph.node.add" params:invalidAdd error:&addError]&&[addAfter isEqual:data()],"Invalid cable cannot leave an orphan plugin");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[addAfter isEqual:data()],"Add at cable survives save/reopen");
  auto connectBefore=data();
  NSDictionary *newSource=@{@"graph":graph,@"kind":@"lfo",@"connect":@{@"node":node,@"port":@1,@"output":@NO,@"modulation":@YES,@"base":@0.4}};
  auto source=call(@"graph.node.add",newSource,true)[@"data"][@"node"];
  auto connected=data();auto mod=[connected[@"library"][0][@"modulation"] lastObject];
  check([mod[@"source"] isEqual:source]&&[mod[@"target"] isEqual:node]&&[mod[@"minimum"] doubleValue]==0&&[mod[@"maximum"] doubleValue]==0&&[mod[@"base"] doubleValue]==0.4,"Creating a source from a parameter socket is atomic and initially silent");
  call(@"history.undo",@{},true);check([connectBefore isEqual:data()],"One Undo removes the source and cable together");
  auto returnBefore=data();auto send=call(@"mixer.bus.add",@{@"kind":@"return",@"sendFrom":target,@"position":@{@"x":@800,@"y":@120}},true)[@"data"][@"bus"];
  auto returnAfter=data();NSArray *sends=returnAfter[@"mixer"][@"buses"][0][@"sends"];
  check([[sends lastObject][@"target"] isEqual:send]&&![[sends lastObject][@"enabled"] boolValue]&&[[sends lastObject][@"gainDB"] doubleValue]==-96,"A new send starts off while its dry route remains intact");
  call(@"history.undo",@{},true);check([returnBefore isEqual:data()],"Return, send and layout creation share one Undo");
  auto groupingBefore=data();NSString *groupingRevision=session.automationRevision;
  call(@"graph.group.create",@{@"graph":graph,@"nodes":@[node,extra],@"name":@"Dynamics",@"dryRun":@YES},true);
  check([groupingRevision isEqual:session.automationRevision]&&[groupingBefore isEqual:data()],"Grouping preview changes neither identity allocation nor history");
  NSString *boundary=call(@"graph.group.create",@{@"graph":graph,@"nodes":@[node,extra],@"name":@"Dynamics"},true)[@"data"][@"group"];
  auto groupingAfter=data();
  for(NSString *key in @[@"nodes",@"audio",@"modulation"])check([groupingBefore[@"library"][0][key] isEqual:groupingAfter[@"library"][0][key]],"Grouping changed processor state or a real cable");
  call(@"history.undo",@{},true);check([groupingBefore isEqual:data()],"A single Undo removes only the processing boundary");
  call(@"history.redo",@{},true);check([groupingAfter isEqual:data()],"Group Redo restores identity and members");
  NSString *nested=call(@"graph.group.create",@{@"graph":graph,@"nodes":@[node],@"parent":boundary,@"name":@"Inside"},true)[@"data"][@"group"];
  auto nestedAfter=data();groupingRevision=session.automationRevision;
  check(![call(@"graph.group.update",@{@"graph":graph,@"group":nested,@"name":@"Inside"},true)[@"changed"] boolValue]&&[groupingRevision isEqual:session.automationRevision],"Identical group edits create no Undo entry");
  NSError *groupError=nil;
  check(![session automationMethod:@"graph.group.create" params:@{@"graph":graph,@"nodes":@[node,extra],@"parent":boundary,@"expectedRevision":session.automationRevision} error:&groupError]&&[nestedAfter isEqual:data()],"Mixed-depth grouping is rejected atomically");
  check(![session automationMethod:@"graph.group.update" params:@{@"graph":graph,@"group":nested,@"name":@"Stale",@"expectedRevision":@"stale"} error:&groupError]&&[nestedAfter isEqual:data()],"Group edits retain revision guards");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[nestedAfter isEqual:data()],"Nested groups persist alongside unchanged recipes and routes");
  call(@"graph.clone",@{@"graph":graph,@"name":@"Grouped copy"},true);
  auto groupedCopy=[data()[@"library"] lastObject];
  check([groupedCopy[@"groups"] count]==2&&![[groupedCopy[@"groups"] firstObject][@"id"] isEqual:boundary],"Cloning allocates independent group identities");
  check([groupedCopy[@"groups"][1][@"parent"] isEqual:groupedCopy[@"groups"][0][@"id"]],"Cloned nested parent references point into the copy");
  call(@"graph.group.remove",@{@"graph":graph,@"group":boundary},true);
  auto remaining=data()[@"library"][0][@"groups"];
  check([remaining count]==1&&[remaining[0][@"parent"] isEqual:@""],"Ungroup preserves child boundaries at the former parent's depth");
  call(@"history.undo",@{},true);check([data()[@"library"][0] isEqual:nestedAfter[@"library"][0]],"Ungroup Undo restores the exact nesting");
  NSString *exportGraph=call(@"graph.create",@{@"name":@"Export fixture"},true)[@"data"][@"graph"];
  NSString *exportNode=call(@"graph.node.add",@{@"graph":exportGraph,@"kind":@"plugin",@"plugin":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1"},@"insertEdge":@0},true)[@"data"][@"node"];
  NSString *exportGroup=call(@"graph.group.create",@{@"graph":exportGraph,@"nodes":@[exportNode],@"name":@"Reusable gain"},true)[@"data"][@"group"];
  auto exportBefore=data();revision=session.automationRevision;
  call(@"graph.group.export",@{@"graph":exportGraph,@"group":exportGroup,@"dryRun":@YES},true);
  check([revision isEqual:session.automationRevision]&&[exportBefore isEqual:data()],"Export preview preserves allocation, source state and history");
  call(@"graph.group.export",@{@"graph":exportGraph,@"group":exportGroup},true);
  auto exportAfter=data();auto exported=[exportAfter[@"library"] lastObject];
  check([exported[@"name"] isEqual:@"Reusable gain"]&&[exported[@"nodes"] count]==3&&[exported[@"audio"] count]==2,"Library export creates an independent playable recipe");
  check([[exportAfter[@"library"] subarrayWithRange:NSMakeRange(0,[exportBefore[@"library"] count])] isEqual:exportBefore[@"library"]],"Export never converts or replaces original processors");
  for(NSDictionary *n in exported[@"nodes"])check(![n[@"id"] isEqual:exportNode],"Export must allocate independent processor identities");
  call(@"history.undo",@{},true);check([exportBefore isEqual:data()],"One Undo removes only the new library entry");
  call(@"history.redo",@{},true);check([exportAfter isEqual:data()],"Export Redo restores the exact independent recipe");
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[exportAfter isEqual:data()],"Exported library recipes survive native save/reopen");
  call(@"plugin.add",@{@"descriptor":@{@"format":@"Built-in",@"classID":@"resonance.gainer.v1",@"name":@"Gain",@"type":@0,@"subtype":@0,@"manufacturer":@0}},true);
  NSString *rackKey=[@"plugin:" stringByAppendingString:[data()[@"plugins"] lastObject][@"id"]];
  auto songGroupBefore=data();revision=session.automationRevision;
  NSDictionary *groupRequest=@{@"nodes":@[rackKey],@"name":@"Rack gain",@"positions":@[@{@"node":rackKey,@"x":@300,@"y":@180}]};
  auto groupPreview=[groupRequest mutableCopy];groupPreview[@"dryRun"]=@YES;call(@"graph.song.group.create",groupPreview,true);
  check([revision isEqual:session.automationRevision]&&[songGroupBefore isEqual:data()],"Song grouping preview preserves the rack and document");
  NSString *songGroup=call(@"graph.song.group.create",groupRequest,true)[@"data"][@"group"];
  auto songGroupAfter=data();check([songGroupAfter[@"groups"] count]==1&&[songGroupAfter[@"plugins"] isEqual:songGroupBefore[@"plugins"]]&&[songGroupAfter[@"mixer"] isEqual:songGroupBefore[@"mixer"]],"Song group wraps existing rack identities without changing their routing");
  call(@"history.undo",@{},true);check([songGroupBefore isEqual:data()],"Song group and initial positions share one Undo");call(@"history.redo",@{},true);check([songGroupAfter isEqual:data()],"Song group Redo restores exact identities");
  revision=session.automationRevision;call(@"graph.song.group.update",@{@"group":songGroup,@"name":@"Rack gain"},true);check([revision isEqual:session.automationRevision],"Identical song group edit is a no-op");
  call(@"graph.layout.set",@{@"groups":@[@{@"group":songGroup,@"x":@400,@"y":@200}]},true);
  auto songGroupMoved=data();bool moved=false;for(NSDictionary *position in songGroupMoved[@"layout"])if([position[@"node"] isEqual:rackKey])moved=[position[@"x"] doubleValue]==400&&[position[@"y"] doubleValue]==200;check(moved,"Song boundary move retains relative processor positions");
  call(@"graph.song.group.export",@{@"group":songGroup},true);auto songGroupExported=data();check([[songGroupExported[@"library"] lastObject][@"nodes"] count]==3,"Song group exports a real independent recipe");
  check([songGroupExported[@"plugins"] isEqual:songGroupBefore[@"plugins"]]&&[songGroupExported[@"mixer"] isEqual:songGroupBefore[@"mixer"]],"Export retains original rack and routes");
  call(@"history.undo",@{},true);check([songGroupMoved isEqual:data()],"Export is one Undo");call(@"history.redo",@{},true);
  check([session savePath:path error:&error]&&[session openPath:path error:&error]&&[songGroupExported isEqual:data()],"Song groups and their independent exports survive native save/reopen");
  call(@"graph.song.group.remove",@{@"group":songGroup},true);check([data()[@"groups"] count]==0&&[data()[@"plugins"] count]==[songGroupBefore[@"plugins"] count],"Ungroup removes only the song boundary");
  [[NSFileManager defaultManager] removeItemAtPath:path error:nil];
  std::cout<<"PASS graph API: preview, identity allocation, guarded atomic edits, assignment and group-capable lanes, Undo/Redo, recipe/state project roundtrip, independent clone identities\n";return 0;
}catch(const std::exception &e){std::cerr<<e.what()<<'\n';return 1;}}}
